### PR TITLE
Taser electrode shot count lowered from 8 to 6

### PR DESCRIPTION
**Pull request by PopNotes**
:cl: PopNotes
tweak: Advanced tasers now have an electrode capacity of 6 instead of 8. The X-01 MultiPhase Energy Gun still has 8.
/:cl:

Was suggested but not changed in #4693

### CODE REVIEW

**Comment by Sarcalogo** [comment]
(F) DEAD: Zheng Jiahao says, "reminder that guyonbroadway removed one hit stuns from security, but gave them to traitors"
(F) DEAD: Zheng Jiahao says, "and chemists"
(F) DEAD: Zheng Jiahao says, "and anyone who is basically not security"
(F) DEAD: Zheng Jiahao asks, "I mean really how did he think that would go?"
(F) DEAD: Zheng Jiahao says, "They have to shoot you once, with an infinite ammo, infinite range weapon."
(F) DEAD: Zheng Jiahao says, "And you have to shoot them twice with a gun that has 8 shots."
(F) DEAD: Zheng Jiahao says, "And fizzles out after 8 tiles or so."
(F) DEAD: Zheng Jiahao says, "SEEMS FAIR RIGHT"

**Comment by dreamcrab** [comment]
ye ok

**Comment by dreamcrab** [comment]
+6

**Comment by GuyonBroadway** [comment]
> but gave them to traitors"
> (F) DEAD: Zheng Jiahao says, "and chemists"

I TRIED TO REMOVE THEM FROM CHEMISTS AND GOT BITCHED AT!

**Comment by Sarcalogo** [comment]
I never bitched at you. Whoever did is dumb.

**Comment by banthebantz** [comment]
+1

**Comment by Arzion5** [comment]
Everything checks out, you can stun 3 people or one person twice, while the HoS gun is untouched. +1

**Comment by WallaceShark** [comment]
I gotta agree with Sarcalogo. Security is in a tough spot right now with their one-hit stuns gone while other departments still have theirs. Paired with the fact that security is always incredibly outnumbered, while also chained down by certain arrest procefures, I don't see this ammo reduction being a good change.

Usually it's four men to one officer. The 8 shot count seems more balanced. -1.

**Comment by PopNotes** [comment]
This isn't just a nerf to security, even though it is, it's a nerf to everyone who steals tasers, and especially those who stack them.

**Comment by WallaceShark** [comment]
If you can come up with a way to reduce the power of taser thieves without dicking over security, you'll have my support. We aren't doing enough to support the uphill game security players face. This change does more harm than good.

**Comment by 2Dollarbill** [comment]
-1, I don't think tasers are in a rough spot, this is more of a nerf to security. To say that it's a nerf to people who steal from security is dumb.

**Comment by Chnkr** [comment]
Your PR needs to be updated to reflect the current state of the master branch, please update your PR and either (re)open it, or ask a maintainer to (re)open it.

**Pull request closed without merging**
