### PR TITLE
Adds mindslave implants

### PR DESCRIPTION
**Pull request by Uqualm**
I noticed that the guy who ported this didn't port my greater mindslave implant, I'll port that AFTER the rebase is finished. ALSO do not merge this until the teleporter PR below it is is merged because I need to modify the uplink list after that is merged.

### CODE REVIEW

**Comment by Uqualm** [comment]
If someone tells me how to resolve this I'll fix it.

**Comment by McBawbaggings** [comment]
```
06:54:10 hippiestation/code/game/objects/items/weapons/implants/implant_mindslave.dm:38:error: ticker.mode.traitors: undefined var
06:54:10 hippiestation/code/game/objects/items/weapons/implants/implant_mindslave.dm:63:error: ticker.mode.traitors: undefined var
```

Change lines 38 and 63 to SSticker.mode.tratiors
I think that'll fix it.

**Comment by McBawbaggings** [comment]
Also if you're not already in the discord, PM and I'll send you a link so you can questions more easily in coderbus.

**Comment by tortellinitony** [comment]
This needs a lot of changes, and I'm not in the mood to review right now. Maybe later.

**Comment by Chnkr** [comment]
I'll review this since @tortellinitony is not in the mood.

Please make use of the new `to_chat` proc and use `Initialize()` over `New()`

**Comment by Carbonhell** [comment]
Fixed in #1614

**Pull request closed without merging**
