### PR TITLE
Removes hygiene for real

### PR DESCRIPTION
**Pull request by KingTerrytheTerrible**
literal waste of cpu power and i'm sick of seeing stink lines on everyone

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
haha stinky lines! stinky lines coder! stinky! uh oh poo poo! poopy! stinky! funny!

**Comment by Manly-Dwarf** [comment]
stinky coder no shower coder smelly coder bad coder

**Comment by QuarianCommando** [comment]
+1

**Comment by karmaisblackandbluepilled** [comment]
literally what does this do

**Pull request merged**
