### PR TITLE
Event gamemode

### PR DESCRIPTION
**Pull request by KingTerrytheTerrible**
rapid fire events

### CODE REVIEW

**Comment by KingTerrytheTerrible** [comment]
thourougly tested

**Comment by mkikt4743** [comment]
+1 seems cool and good, also relieves us from constant wiz/traitor rounds on lowpop

**Comment by Manly-Dwarf** [comment]
this is basically just extended

**Comment by KingTerrytheTerrible** [comment]
except there's an event every minute or so

**Comment by Manly-Dwarf** [comment]
we should honestly get around to buffing some events as well
i miss the disease event not always giving a god damn "advanced" disease that does nothing

**Comment by Ledwin1233** [comment]
You can buff the disease event by making it aim for the maximum of one stat with all its symptoms, max stealth, max transmission, only one of them but it'll make it pretty nice

**Comment by Manly-Dwarf** [comment]
no fuck that shit
remove the advanced disease option entirely
the precoded diseases are not only more fun, but they're typically deadlier too

**Comment by zamolxius** [comment]
honestly this either make the advanced disease budget bigger or something,  or make only preset ones.  way better and more polished

**Comment by cris5311** [comment]
+1 
events funny

and yes disease event is boring as is

**Comment by karmaisblackandbluepilled** [comment]
what does this do

**Pull request closed without merging**
