### PR TITLE
fixes vox login sound

### PR DESCRIPTION
**Pull request by Blute1**
have a secure day

:cl: Spacedong
fix: fixed vox_login sound
/:cl:

### CODE REVIEW

**Comment by banthebantz** [comment]
>5 commits
>1 file changed

**Comment by Blute1** [comment]
also, for reference, the old sound file was bugged and cut off after 1 second
https://github.com/HippieStationArchive/HippieStation13-1/blob/master/sound/vox/vox_login.ogg

**Comment by JohnGinnane** [comment]
@blute1 why does it repeat "base" I think?

**Comment by McBawbaggings** [comment]
because it's an old hippie meme

+1

**Comment by JohnGinnane** [comment]
Just occurred to me this a fix, so gonna merge anyway

**Pull request merged**
