### PR TITLE
Removes blob

### PR DESCRIPTION
**Pull request by Mlgdatboiwew**
:cl: Mlgdatboiwew
del: Blob
/:cl:

Flux is being a annoying asshat and cant do this himself so I will do it.I dont suggest removing blob as its a fun gamemode but I dont care.

### CODE REVIEW

**Comment by Mlgdatboiwew** [comment]
I cant modulize a removal dont blame me

**Comment by Thelolswat** [comment]
Couldnt you just turn the weight to 0 or whatever, to take it out the rotation?

**Comment by DinduStuffin** [comment]
-1
I don't think the mode needs a full on removal, it needs tweaking. Let's not jump the gun here.

**Comment by Mlgdatboiwew** [comment]
I dont want it removed either

**Comment by DinduStuffin** [comment]
wait what the fuck did you just gut out mentions of it entirely?

**Comment by TDcoolguy300** [comment]
This is not how you to this, just have someone change the bloody configuration serverside

**Comment by Mlgdatboiwew** [comment]
@Dindu

**Comment by DinduStuffin** [comment]
@Maverick#1714

**Comment by TDcoolguy300** [comment]
@TDcoolguy300#6472

**Comment by PopNotes** [comment]
-1

**Comment by 2Dollarbill** [comment]
+1
Blob is abysmal to play on hippie station, we had it removed for a reason and I don't mind to have it removed again.

**Comment by DinduStuffin** [comment]
2dolla you don't understand
whether you hate blob or not, the way he's trying to remove it will no doubt fuck up SOMETHING on the server. I think this should be denied and have someone else (td, amari, bluescope, etc) handle it

hell just ping McBaw and tell him to set the chance for blob to 0 or something
this is NOT the solution by any means

**Comment by Pyko1** [comment]
Just use config if you don't want to have blob as a gamemode.

You would have to manually edit tons of files to remove blob completely.

**Pull request closed without merging**
