### PR TITLE
HippieStation tiles

### PR DESCRIPTION
**Pull request by Uqualm**
Area above bridge now says HippieStation.

### CODE REVIEW

**Comment by Uqualm** [comment]
This worked in the old pull request, and I did the exact same thing here, yet the changes are not reflected. I compiled hippie instead of tg and ran it, still showed up as Space Station. I'm thinking something to do with how I ran it rather than the changes not working.

Why didn't it work?

**Comment by Carbonhell** [comment]
Wouldn't it be better to make a dmi for hippie floor icons, add the icons there and make new turfs for this kind of floor?It's longer, but it'll be completely modularized atleast

**Comment by Sarcalogo** [comment]
Yes I know what you mean, but then I'd have to edit the map and I don't feel like doing that. I'll do it later today.

**Comment by banthebantz** [comment]
Uqualm == Sarcalogo?

**Comment by Sarcalogo** [comment]
Yes.

**Comment by JamieH** [comment]
I guess, dunno why they're using a different GitHub for the PRs but we appreciate the contributions who ever it is.

**Comment by Sarcalogo** [comment]
You can't fork a fork and what the fork forks, so I had to use two accounts.

**Comment by JamieH** [comment]
You can fork a fork as long as you don't have any other forks of the base or the base cloned.

**Comment by Sarcalogo** [comment]
Right, but I forked /tg/ so I can't fork both Hippie and /tg/.

**Comment by GuyonBroadway** [comment]
You can delete your tgfork and then fork hippie...

Unless you want a tgfork.

**Comment by Sarcalogo** [comment]
Yes, I do want a /tg/fork.

**Comment by Sarcalogo** [comment]
Huh.. I forgot about this. Will finish this and a few other items on the todo list tomorrow

**Pull request closed without merging**
