### PR TITLE
Today I will fix combat by making it tile-based

### PR DESCRIPTION
**Pull request by karmaisblackandbluepilled**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
tweak: checks for mobs in tiles when handling meleeing instead of checking for the mob sprite
/:cl:

## About The Pull Request
since steamport won't work on swing combat this is the next best thing

## Why It's Good For The Game
because pixel-hunting is mad gay, this is better™. It makes people with lag have a better chance of hitting people too, probably

oh yeah I should mention that I didn't make this, I just stole it from a pr from 2015

### CODE REVIEW

**Comment by notoriousBIGGIOS** [comment]
nice

**Comment by karmaisblackandbluepilled** [comment]
biggi vote +1 right now or so help me God

**Comment by steamp0rt** [comment]
oh no

**Comment by karmaisblackandbluepilled** [comment]
It's happening.

**Comment by ErwinSnowden** [comment]
Horrible fucking idea that will make it so much easier to use nearly every weapon including the HF blade. This will buff Good Boy and buff laggy players. Also does it work for simplemobs? If it doesn't, severely unbalanced.

**Comment by zamolxius** [comment]
it passed the checks, can we have a testmerge?

**Comment by Toxici11i** [comment]
Make it so stunbatons cannot be used in this way

**Comment by zamolxius** [comment]
> Make it so stunbatons cannot be used in this way

cringe. just git gud at stay at range. 
alternatively, we could make stunbatons just deal 50-75 stamina when hitting

**Comment by FantasticFwoosh** [comment]
I guess people with bad ping are going to be playing what is essentially final fantasy tactics then, cool-beans. Real actual problem though is that this doesn't actually make hitting people with [alt] to view a turf harder though does it?

**Comment by karmaisblackandbluepilled** [comment]
erwin who are you, is it you hibiki? Also, it works for every mob, and simplemobs count as mobs.
@Toxici11i  I don't think I can do that
@FantasticFwoosh as far as I get see it, it makes the game more playable for bad ping dumbasses. It doesn't make alt-hitting harder since I didn't touch the alt click code.

**Comment by mikolaj007** [comment]
assuming it works, +1

**Comment by Toxici11i** [comment]
wait @karmaisblackandbluepilled oh god oh fuck, what if multiple people are stacked on the same tile?

**Comment by zamolxius** [comment]
> wait @karmaisblackandbluepilled oh god oh fuck, what if multiple people are stacked on the same tile?
> 
> edit: if it hits all of them, fix that. being able to stun 6 or so people as wizard, get plasmafist, and combo them while they are stunned ontop of eachother, gibbing all of them will be uh...

would be very cool in any case

**Comment by karmaisblackandbluepilled** [comment]
@Toxici11i hits one person at random, not all at once

**Comment by MaterialisticThings** [comment]
This takes skill out imo but we can give it a shot and see how it works

**Comment by cris5311** [comment]
if it works its a hard +1 for me, but we should test merge it first

> alternatively, we could make stunbatons just deal 50-75 stamina when hitting

that would be mega gay, were not some citrus fruit

**Comment by diegoxt45** [comment]
sure.... +1

**Comment by Manly-Dwarf** [comment]
not a real fix for melee combat
-1

**Comment by ExpAntique** [comment]
-1

**Comment by Toxici11i** [comment]
-1, if this is merged hippie will die

**Comment by zamolxius** [comment]
keep in mind this is not only tilebased, it also activates when you click in the direction of the enemy. this would make weapons actually relevant when compared to projectiles @Manly-Dwarf

**Comment by yoyobatty** [comment]
What happens when you try to click an item in the same tile or alt click stacked bodies

**Comment by karmaisblackandbluepilled** [comment]
click the item and you take the item, altclick and the altclick menu opens, doesn't matter how many people are on the same tile.

**Comment by zamolxius** [comment]
testmerge and see the playerbase reaction

**Comment by DON-KARMA** [comment]
retarded, fuck you

**Comment by karmaisblackandbluepilled** [comment]
it's fucked, someone add the do not merge until I fix it

**Comment by karmaisblackandbluepilled** [comment]
thank you steamporb

**Comment by karmaisblackandbluepilled** [comment]
i deleted the folder I made this in so I'm closing this and remaking the pr once I fix it

**Pull request closed without merging**
