### PR TITLE
Ash lizards don't fall over and take damage when stepping on glass shards 

### PR DESCRIPTION
**Pull request by Spacedong**
>live on fiery hellworld where everything is rocky and dangerous
>woops my feet are sensitive and slip on glass shards :/
fuck TG

:cl: Spacedong
tweak: Ash lizards can safely step over glass shards now.
/:cl:

### CODE REVIEW

**Comment by praisenarsie** [comment]
do this upstream

**Comment by banthebantz** [comment]
nah fuck them

**Comment by Arzion5** [comment]
>Step on cactus
>Fall over
I don't see what's the problem

**Comment by McBawbaggings** [comment]
I think our ashliggers are different codewise anyway so doing this upstream isn't really a good thing for us since we'll have to modularise the change anyway.
I don't like ash liggers but it is dumb they got snowflake feet but can't wear shoes to protect them from fucking shards. I support the change and it's kinda thematic that they don't care about glass.

**Comment by banthebantz** [comment]
also remove the digitigrade flag and have them start with shoes dont make them immune to all embeds and syringes wtf

**Comment by PopNotes** [comment]
>dont make them immune to all embeds and syringes wtf
(((spacedong)))

**Comment by McBawbaggings** [comment]
okay i thought pierceimmune was just glass shards only

yeah, just make it so they can wear shoes and they spawn with leather sandals or something then

**Comment by Spacedong** [comment]
THATS MORE WORK FUCK

**Comment by Spacedong** [comment]
digitigrade looks cooler though and plus why the fuck is there not a specific define for being able to step over glass shards? why lump it in with piercing? fuck

**Comment by Pyko1** [comment]
give em virtual shoes called hardened feet soles.
And make sure its no drop.
And bother someone to make icon for digitigrade feet to be used as shoe icon.

**Comment by tortellinitony** [comment]
Just edit the flag so you can't step on glass with it maybe? This is not a good way of implementing this change

**Comment by MoreRobustThanYou** [comment]
@Spacedong upstream this. If they don't accept it, THEN bring it here.

**Pull request closed without merging**
