### PR TITLE
Better on-hit sound for officer's sabre

### PR DESCRIPTION
**Pull request by PopNotes**
:cl: PopNotes
soundadd: [stabbing noises]
/:cl:

Before: http://puu.sh/wexF8/01bcb68474.ogg
After: http://puu.sh/wexGs/2ebb5c2fa7.ogg

### CODE REVIEW

**Comment by Chnkr** [comment]
Please put a before/after preview in the PR body

**Comment by PopNotes** [comment]
Done and done.

**Comment by Chnkr** [comment]
Looks good to me

**Comment by McBawbaggings** [comment]
yeah this is gucci 👌

**Pull request merged**
