### PR TITLE
Removes the Build Your Own Shuttle Kit from the purchasable shuttles list

### PR DESCRIPTION
**Pull request by PopNotes**
:cl: PopNotes
del: Goodbye, Build Your Own Shuttle, nobody will miss you.
/:cl:

I don't know anyone who doesn't hate this piece of shit. The only reason I have ever seen anyone buy it is to be a le epic trel, forcing people to use pods. The amount of times I've heard "Welp, clown busted into bridge and bought the kit, guess we don't get to have a shuttle party." is stupidly high.

Even the asteroid, the _fucking_ asteroid is a better shuttle, since it arrives with its own atmos.

Delet this.

### CODE REVIEW

**Comment by McBawbaggings** [comment]
+1

fuck the meme, you're basically fucking over the escape shuttle and everyone else for it.

also comment the whole thing out, not the class definition line or else it won't work.

**Comment by PopNotes** [comment]
gotchu fam

**Comment by tortellinitony** [comment]
no have it be added to the restricted list on the config

**Comment by GuyonBroadway** [comment]
To be fair, as caotain dwright would buy this every damn time.

Buying it should force the shuttle launch timer to beba good 10 mins and is not fastlaunchable

**Comment by PopNotes** [comment]
Actually I think this was changed in the config so I'll just go ahead and baleet this

**Pull request closed without merging**
