### PR TITLE
Ebow changes

### PR DESCRIPTION
**Pull request by PopNotes**
:cl: PopNotes
balance: Shots from the mini energy crossbow now paralyze the target in place for three seconds, causing them to drop their weapon. They also induce heavy slurring and stuttering for ten seconds after being shot, making it very difficult to accurately call for help.
balance: Recharge time on the mini energy crossbow is four seconds, allowing the target only one second to fight back before another bolt can be put into them.
balance: Ebow bolts have had their damage raised from 8 to 15.
balance: Price has subsequently been lowered to 8 telecrystals, reinforcing its purpose as a combo weapon instead of a one-click stunlocker.
soundadd: An actual ebow sound!
/:cl:

### CODE REVIEW

**Comment by JohnMcLaime** [comment]
Detectives gun should be next, if it still one hit stuns (havent played in a couple of weeks).

**Comment by GuyonBroadway** [comment]
@JohnMcLaime the detectives gun stunning was a bug that I fixed. It was due to a projectile name refactor.

**Comment by dreamcrab** [comment]
nah

**Comment by Arzion5** [comment]
>Shots from the mini energy crossbow now paralyze the target in place for three seconds, causing them to drop their weapon.



>Price has subsequently been lowered to 8 telecrystals, reinforcing its purpose as a combo weapon instead of a one-click stunlocker.

**Comment by tortellinitony** [comment]
:hankey:

**Comment by PopNotes** [comment]
build this

**Comment by banthebantz** [comment]
i wanna wait for guyon's idea -1

**Comment by Kawaii-Big-Boss** [comment]
Is this grudgecode?
Also, terrible idea. A paralyze + weapon drop is usually more than enough to completely screw someone over with an esword. On top of that, reducing the price just means that traitor can now buy EMP Implants or No-Slips which just makes them harder to take down.
The Ebow is fine, stop trying to change it.

**Comment by PopNotes** [comment]
The point is that it's SUPPOSED to be something that gives you enough time to fuck someone over with something like an esword, the ebow as is is something you can use to murderbone the entire station with alone and that's gay, also hard ten second ranged stuns are shit

**Comment by Kawaii-Big-Boss** [comment]
Why would you want to buff one of the most hated traitor combos and nerf everything else about the ebow?
You're just restricting its use to the easiest, least original means to kill the whole station and nothing else.

**Comment by PopNotes** [comment]
I never said the only other thing you should use it with is an esword, that has to be an intentionally stupid point you're making. The idea here is that it turns the ebow from a near-silent, low-damaging, ten-second stun weapon with infinite shots and a two second recharge to a near-silent, slightly-better-damaging, three-second stun weapon with infinite shots and a four second recharge. It still essentially retains the same idea as the original while being far more combo oriented with something in your offhand after you get a shot off (run up and stun baton, esword, fill with bullets, steal their weapon and use it on them, something something krav maga, spray with chem bottle, spam shuriken etc.)

**Comment by Kawaii-Big-Boss** [comment]
The original ebow had multiple shots that could be held at once, making it spammy as all hell. It's a good thing we drove away from that.

But what is the point of making it "combo oriented"? If the ten second recharge is a problem then reduce the stun time, no need to completely rework it into some "combo weapon" when the ebow is good solely because it's just a basic stun. You can pair a basic stun in the game with literally anything.
Having to run up and slap someone with a stunbaton won't change much, considering that most of the time people will immediately draw an epen or an esword and go hog wild. This just adds one step and then lets them buy more stuff.
Not using the esword immediately with the ebow with this change would be stupid, especially because you buffed the ebow's damage to 15 which lets the esword crit people in 3 hits instead of 4.

**Comment by PopNotes** [comment]
You keep saying "combo weapon" like that's not its intended purpose. It sounds to me like that's the part you're most skeptical about, for some reason.

Let me break this down to be more digestible for you: Old ebow was all you needed to murderbone the station. New ebow is a companion weapon, not a standalone weapon.

I'm thinking about raising the stun time to 5 seconds and recharge to 6, so the assailant has a little more time to act. It's still a heavy nerf, but I'm thinking 3 seconds might be a bit **too** short.

**Comment by Kawaii-Big-Boss** [comment]
But why do you think this change is necessary?
What makes you think that this is a good rework for a popular Traitor item that's known for being able to combo with anything, or just be a reliable weapon on its own?

**Comment by PopNotes** [comment]
it's

# boring

and

# gay

**Comment by Kawaii-Big-Boss** [comment]
So this is grudgecode because some guy killed you with the ebow?
The esword is a pretty boring weapon on its own, too. Doesn't mean we should rework it completely.

**Comment by JohnMcLaime** [comment]
Up reload time by 1 second or decrease the on hit effect by 1 second and it would be fine.
You dont even need to buy esword with current ebow, you can either use nearest extinguisher or just stunlock them till they die from toxins.

**Comment by Arzion5** [comment]
I am ok with this, the stun is now more in balance with our stun rework and the price has been adjusted accordingly. +1, but I want to give feedback that people will still understand what someone's trying to say beyond all the slurring and the stuttering.

**Comment by 2Dollarbill** [comment]
No. I think the ebow is fine as it is, it doesn't need "changes" much less more so it's nerfs that you've proposed.

**Comment by Chnkr** [comment]
Your PR needs to be updated to reflect the current state of the master branch, please update your PR and either (re)open it, or ask a maintainer to (re)open it.

**Pull request closed without merging**
