### PR TITLE
Adds Carborane acid

### PR DESCRIPTION
**Pull request by Mlgdatboiwew**
:cl: Mlgdatboiwew
add: A extremely strong acid
/:cl:

Why?Well you can use this acid to kill your enemies.2 Syringe fulls can kill even the strongest of enemies even though you will be thrown into space!

### CODE REVIEW

**Comment by MoreRobustThanYou** [comment]
holy crap it seems OP, especially since it's easy to make.

**Comment by Mlgdatboiwew** [comment]
idk

**Comment by TDcoolguy300** [comment]
Can i carbonate drinks with it?

**Comment by Mlgdatboiwew** [comment]
Its not that type of carbonation

**Comment by TDcoolguy300** [comment]
I want to carbonate drinks with it

**Comment by Mlgdatboiwew** [comment]
Drinks come carbonated from the bar machines

**Comment by TDcoolguy300** [comment]
I want my other non-carbonated drinks to be carbonated

**Comment by PopNotes** [comment]
get the fuck off this earth

**Comment by DinduStuffin** [comment]
-1
too op, will be abused
people like yobihodazine are living proof that chemistry absolutely must be balanced

**Comment by 2Dollarbill** [comment]
Would like it as a traitor item possibly.

**Comment by Mlgdatboiwew** [comment]
we need more chemistery pls

**Comment by TDcoolguy300** [comment]
Carbonation

**Comment by banthebantz** [comment]
OP, isn't casschem autism and uses a bunch of copypaste code.

nah

**Comment by banthebantz** [comment]
Also Carborane acid isn't the strongest AFAIK

**Comment by McBawbaggings** [comment]
you know from the days of trekchem
i have no idea if pcaid was fine or OP
but frankly, it's probably for the best to not figure that one out.

**Comment by banthebantz** [comment]
you could crit people in about 2 5u sprays my man

**Comment by JamieH** [comment]
-1

**Comment by tortellinitony** [comment]
Why though?

**Pull request closed without merging**
