### PR TITLE
[READY] A Rather Large Escape Shuttle

### PR DESCRIPTION
**Pull request by k-k-karma**
:cl: karma
add: a new escape shuttle - "A Rather Large Escape Shuttle!"
/:cl:

disclaimer: not actually that large
is tested

### CODE REVIEW

**Comment by BlueNothing** [comment]
Can you add a picture?

**Comment by k-k-karma** [comment]
its in the map diff bot renders

**Comment by DaydreamPuppeh** [comment]
+1

**Comment by xTrainx** [comment]
Neat +1

**Comment by t-f-w** [comment]
+1

**Comment by bardofrage** [comment]
+1

**Comment by k-k-karma** [comment]
ready 2 merge

**Pull request merged**
