### PR TITLE
Adds energy katana to traitor uplink at steep cost

### PR DESCRIPTION
**Pull request by Swagile**
adds ekatana, nuff said

balanced it a bit more by making it BULKY, so you can't wear it on anywhere except your belt, so you sacrifice your belt slot and can't bag it, hence buying this item means your going full LOUD

18 TC so the only thing you can really buy after that is some no slips or gimmick items

### CODE REVIEW

**Comment by PopNotes** [comment]
Nnnnnnnooooot really feeling this. The e-katana is, like, one of the best melee weapons in the entire game.

**Comment by dreamcrab** [comment]
nooooooooooooo

**Comment by dreamcrab** [comment]
-1337

**Comment by Swagile** [comment]
i have to make this modular, gunna close it and try again

**Pull request closed without merging**
