### PR TITLE
Minor fart buffs and fixes

### PR DESCRIPTION
**Pull request by k-k-karma**
:cl: karma
balance: items no longer drop out your ass while farting
fix: removed bugged fart message
/:cl:

### CODE REVIEW

**Comment by Carbonhell** [comment]
aw why, farting out items was fun

**Comment by k-k-karma** [comment]
so i can spam megaphone farts

**Comment by zamolxius** [comment]
farting out items is a good thing.  its just natural,  the gas cant go out without pushing the object right? -1

**Comment by yoyobatty** [comment]
Reduce the chance of items falling out to like 10 or 15 and we'll call it a day.

**Comment by DaydreamPuppeh** [comment]
No keep it. I like to fart out lighters

**Pull request closed without merging**
