### PR TITLE
Disables Blob

### PR DESCRIPTION
**Pull request by Mlgdatboiwew**
:cl: Mlgdatboiwew
add: A file for disabling gamemodes
tweak: Disables blob
/:cl:

I don't think people wanted all references to blob removed so I instead referenced it in a DM and set the probability to 0.

### CODE REVIEW

**Comment by PopNotes** [comment]
-1

**Comment by lordpidey** [comment]
Take a look at #3390, that's how you enable/disable gamemodes, not by hardcoding it.

**Comment by MoreRobustThanYou** [comment]
This is NOT how you disable gamemodes.

**Comment by Mlgdatboiwew** [comment]
jesus I give up you do it

**Comment by blobbernaut** [comment]
wtf did i do stop don't

**Pull request closed without merging**
