### PR TITLE
Fixes bluespace capsules

### PR DESCRIPTION
**Pull request by Uqualm**
They can't be used on station anymore.

### CODE REVIEW

**Comment by Uqualm** [comment]
Ah woops let me fix that.

**Comment by Uqualm** [comment]
Now it's in the HippieStation folder.

**Comment by McBawbaggings** [comment]
in the hippiestation.dme file, untick the the old mine_items.dm and tick the new mind_items.dm
We have 2 .dme files. We run the hippiestation.dme and don't tounch the tgstation.dme to minimise conflicts.

**Comment by Uqualm** [comment]
Not sure what the problem here is. Just a bunch of similar lines of code

`09:37:38 code/modules/mining/mine_items.dm:88:error: digspeed: duplicate definition`

Do I have to delete the repeated coded again?

**Comment by Uqualm** [comment]
Well I have no idea how to resolve this and will fix it when someone tells me what to do.

**Comment by McBawbaggings** [comment]
Okay, ignore the whole mounting and unmounting files thing. In this case, you're free to modify the base /tg/ file without recreating it in the hippiestation folder.

To clarify, BYOND is now seeing 2 versions of a file with the same procs and variables and such. It can't tell which version to use. If you're going to override some procs in a file then you would have to disable the file in the hippiestation.dme by unticking it on the left hand side of dream maker. Then you would enable your new file in the hippiestation folder by ticking that file instead.

Now, while we do try to modularise the code when we can, it's not always possible or reasonable to do so. Since you're modifying a single proc in one big file, it's more sensible to just make the change on base file rather than recreate it.

There's also a bug, on your check to see if it can be used on the station. There's a boolean flag "used" that determines if the capsule has been used. It gets set to TRUE when you activate it until it cannot be used. Which it resets back to FALSE. Line 57 shows this in action. Since you want the pod to be used again if it cannot be deployed but you return in your if statement without resetting the boolean flag, it's gonna perma break on that check. Just add "used = TRUE" just before the return statement.

Currently, your build is failing because you've redefined the same proc in both files.
Simply just delete the hippiestation version of your file, don't worry about modularising this file.
Make sure hippiestation.dme has the file you made no longer ticked.
Just replace the proc in the original file with your new one along with the new can_be_used_on_station flag you made in the file definition.

If you need any more help, I'll try my best to explain further.

**Comment by Uqualm** [comment]
Is there some sort of 
@OVERRIDE 
I can use to just override a certain section of code? 

Also That is intended by the person who added it. It's supposed to break if tried to use on station, not just fail to deploy. I tested it in my very first pull request that made the changes.

**Comment by McBawbaggings** [comment]
Generally speaking if you're adding new functionality to something, make a new file with the procs. If you have to make minor changes to the file directly, do that. If you have to rework the file entirely, make a new file and mount that version instead of the old one.

As said, delete the new file you made in the hippiestation directory and just modify the base file in this case. You'll only have 1 proc definition.

**Comment by Uqualm** [comment]
Alright, that's that. It's done.

**Comment by Uqualm** [comment]
Too many commits. Will close and re-open with just one commit.

**Comment by McBawbaggings** [comment]
I'm retarded! It should be used = TRUE
Apologies.

**Comment by Uqualm** [comment]
Yes, I figured that out when I was testing it.

**Comment by McBawbaggings** [comment]
Also we can squash commits so it's a single commit.

**Comment by Uqualm** [comment]
Also figured out that I made a nested if statement NOT a nested if statement, which meant that the bluespace capsules just didn't work period. I'm fixing that now.

**Comment by Uqualm** [comment]
https://github.com/HippieStation/HippieStation/pull/1146

**Pull request closed without merging**
