### PR TITLE
Oof: The Pull Request

### PR DESCRIPTION
**Pull request by PopNotes**
:cl: PopNotes
soundadd: Slipping now has a chance for greatness.
/:cl:

### CODE REVIEW

**Comment by Arzion5** [comment]
Yes

**Comment by DinduStuffin** [comment]
+1
do it

**Comment by bardofrage** [comment]
Oof. Approved +1

**Comment by Dudeinyourbackyard** [comment]
i hate fun
i cannot support this
_oof_
-1
great for april fools though even though that's a million years away now

**Comment by McBawbaggings** [comment]
keep this for april fools next year imo

**Comment by PopNotes** [comment]
lemme offer a compromise, two admins and a head want it whereas the other two don't or are conflicted

why don't we merge it for now and revert once people get tired of it

**Comment by JamieH** [comment]
God no, you could maybe have it as a random chance instead of the normal one though?

**Comment by PopNotes** [comment]
done

**Comment by MoreRobustThanYou** [comment]
what could go wrong

**Pull request merged**
