### PR TITLE
Adds old hair

### PR DESCRIPTION
**Pull request by Uqualm**
Now you have the old hair.

### CODE REVIEW

**Comment by optimumtact** [comment]
THAT'S A LOT OF HAIR

**Comment by Uqualm** [comment]
It's not that much just 10 or so.

**Comment by JamieH** [comment]
We don't need to replace the whole file here, only add our custom hairstyles

```/datum/sprite_accessory/hair/birdnest
	name = "Birdnest"
	icon = 'hippiestation/icons/mob/human_face.dmi'
    icon_state = "hair_birdnest"

/datum/sprite_accessory/hair/unkept
	name = "Unkept"
	icon = 'hippiestation/icons/mob/human_face.dmi'
    icon_state = "hair_unkept"

/datum/sprite_accessory/hair/duelist
	name = "Duelist"
	icon = 'hippiestation/icons/mob/human_face.dmi'
    icon_state = "hair_duelist"

/datum/sprite_accessory/hair/fastline
	name = "Fastline"
	icon = 'hippiestation/icons/mob/human_face.dmi'
    icon_state = "hair_fastline"

/datum/sprite_accessory/hair/modern
	name = "Modern"
	icon = 'hippiestation/icons/mob/human_face.dmi'
    icon_state = "hair_modern"

/datum/sprite_accessory/hair/quadcurls	//weaboo supreme
	name = "Quadcurls"
	icon = 'hippiestation/icons/mob/human_face.dmi'
    icon_state = "hair_quadcurls"

/datum/sprite_accessory/hair/rapunzel
	name = "Rapunzel"
	icon = 'hippiestation/icons/mob/human_face.dmi'
    icon_state = "hair_rapunzel"

/datum/sprite_accessory/hair/unshaven_mohawk
	name = "Unshaven Mohawk"
	icon = 'hippiestation/icons/mob/human_face.dmi'
    icon_state = "hair_unshavenmohawk"

/datum/sprite_accessory/hair/twincurl
	name = "Twincurls"
	icon = 'hippiestation/icons/mob/human_face.dmi'
    icon_state = "hair_twincurl"

/datum/sprite_accessory/hair/twincurl_alt
	name = "Upper Twincurls"
	icon = 'hippiestation/icons/mob/human_face.dmi'
    icon_state = "hair_twincurl2"
```

**Comment by Uqualm** [comment]
Huh.. so it only appends the contents of the file to the /tg/ file on compilation or something?

**Comment by JamieH** [comment]
@Uqualm - nah, but the way the headcode works is it gets all types of `/datum/sprite_accessory/hair` and adds it to the list, it doesn't matter where you define it.

**Comment by Uqualm** [comment]
There.

**Comment by JamieH** [comment]
You still need to override the icon on each of these: `icon = 'hippiestation/icons/mob/human_face.dmi'`

**Comment by Sarcalogo** [comment]
There we go, got it working.
it works

**Pull request merged**
