### PR TITLE
Screechisol no longer does toxin damage

### PR DESCRIPTION
**Pull request by PopNotes**
:cl: PopNotes
balance: Screechisol no longer does toxin damage.
/:cl:

It's a memechem with the side effect of being dangerous if enough is ingested, not a murderchem with the side effect of being memey.

### CODE REVIEW

**Comment by tortellinitony** [comment]
it's still a murderchem since it makes people scream when they're already unconscious

**Comment by PopNotes** [comment]
@tortellinitony It takes awhile to actually kick in with enough screaming to do serious damage and is easily countered by the epipen that literally every single person spawns with.

**Comment by tortellinitony** [comment]
ok but that doesn't change the fact that it's still a murderchem. the scream chemical pre rebase wouldn't kill people cause it stopped when they passed out

**Comment by banthebantz** [comment]
silly sausage

**Comment by PopNotes** [comment]
ok but that doesn't change the fact that it's completely nullified by epinephrine

nearly everything is a murderchem in the right dosage, especially omnizine

**Comment by tortellinitony** [comment]
That's true, but omnizine has actual functions other than just being a joke. There are also chemicals which are very good at killing people, but they're intended to do that, and from the looks of it this chemical isn't?

**Comment by PopNotes** [comment]
build this

**Comment by banthebantz** [comment]
+1

**Comment by Dudeinyourbackyard** [comment]
+1

**Comment by Arzion5** [comment]
Screechisol can now be used as a relatively harmless memechem, as long as you do not overdose. +1

**Comment by WallaceShark** [comment]
+1. Meme on.

**Comment by 2Dollarbill** [comment]
Meme chem should not let you take damage, +1

**Comment by Chnkr** [comment]
Your PR needs to be updated to reflect the current state of the master branch, please update your PR and either (re)open it, or ask a maintainer to (re)open it.

**Pull request closed without merging**
