### PR TITLE
Removes retard horn

### PR DESCRIPTION
**Pull request by Blute1**
removed an atrocity completely from the codebase, I don't want to say what it does, but its very bad, and you can tell from looking at the code. Whoever designed this item deserves 200 brain damage.
:cl: Spacedong
del: Removed the extra annoying airhorn item from the game.
/:cl:

### CODE REVIEW

**Comment by SplergeBucket** [comment]
needs to happen
we honked it six times and at 60 brain damage it instantly killed five people around it
iunno what the balance is on this thing but it needs to be reconsidered lmfao

**Comment by Blute1** [comment]
i think this warrants an instant removal because this is just so thoroughly disgusting

**Comment by Dudeinyourbackyard** [comment]
destroy it

**Comment by Blute1** [comment]
just merge it yourself

**Comment by Blute1** [comment]
dont you have merge rights

**Pull request merged**
