### PR TITLE
Old Airlock sounds

### PR DESCRIPTION
**Pull request by Uqualm**
Just changes the sounds on the doors to the old ones. Didn't think it prudent to create a whole new file just to change one variable that will never be touched, so edited the /tg/ code.

### CODE REVIEW

**Comment by Uqualm** [comment]
McBawbaggings told me the following:

>Now, while we do try to modularise the code when we can, it's not always possible or reasonable to do so. Since you're modifying a single proc in one big file, it's more sensible to just make the change on base file rather than recreate it.

Please tell me why that is not the case here.

**Comment by McBawbaggings** [comment]
Recreating a 1000+ line file for 2 changes is silly. I don't see this should be modularised

**Comment by Uqualm** [comment]
And clear this up for me as well someone because I see some problems down the line if you insist on "modularizing" for every small detail. We have a Hippiestation folder and all code in that folder overrides the /tg/ folder correct? 

So let's say six months from now, we make minor changes to a great deal of things collectively that have to be made in large files. Now /tg/ does a major feature that also effects these large files that we have HippieStation versions of. So now in order to port that we have to manually port it right? Because the changes made by the MIRROR PR won't actually affect us because we are already overriding the base code?  So won't this sort of kill the mirror system given enough time?

Am I right or am I missing something?

**Comment by Uqualm** [comment]
And conversely, let's say we make a minor change to a big file that is likely to be touched. Won't our minor change be overwritten in such large PR's if we DON'T add a Hippie version? It seems like both approaches have their downsides, but one comes at a cost of losing minor functionality and another comes at a cost of losing out on porting major functionality. 

Again, I'm not sure because I don't entirely understand how the system works but if I'm right I predict this being a huge problem.

**Comment by Uqualm** [comment]
Until that is resolved and I have my answer I will continue to make minor changes on the /tg/ files because it makes the most sense.

**Comment by tortellinitony** [comment]
In `hippiestation\code\game\machinery\doors\airlock.dm`, you will want to create this:

`/obj/machinery/door/airlock/var/doorClose = 'sound/machines/airlock.ogg'
/obj/machinery/door/airlock/var/doorDeni = 'hippiestation/sound/machines/denied.ogg'
/obj/machinery/door/airlock/clown/doorClose = 'sound/items/bikehorn.ogg'`

And it's as simple as that

**Comment by Uqualm** [comment]
Isn't that what I did? I see that you have the object name before the variable? Why?

**Comment by tortellinitony** [comment]
This is very clearly not what you did, since you modified the original files.

**Comment by Uqualm** [comment]
Oh I see, I thought that HippieStation was the root directory but it's the hippie folder.

**Comment by Uqualm** [comment]
Now can you answer my question up above?

**Comment by tortellinitony** [comment]
You are able to define variables in a number of ways. If you want to have the indentation:

`/obj/machinery/door/airlock
     var/doorClose = 'sound/machines/airlock.ogg'`

then that should work, too. However, if it is saying that the variable is already defined, you can just have doorClose -- I am not certain if you need to redefine it when putting it in this new file.

**Comment by Uqualm** [comment]
No I mean the big paragraph long question.

**Comment by tortellinitony** [comment]
You have to add the new file to the .dme file like anything else.

**Comment by Uqualm** [comment]
Well there we go.

**Comment by tortellinitony** [comment]
Test it, and if you can confirm it works I will merge this.

**Comment by tortellinitony** [comment]
OK so you can change it to be like you have the variables normally, so just do /obj/machinery/door/airlock and underneath just have `doorClose = whatever`

**Comment by Uqualm** [comment]
What you told me was wrong. I'm getting an error that says duplicate definition, which means I can't actually override variables which means I need to recreate the whole file or add it to the /tg/ code. I'm reluctant to do that recreating a whole new file until my question has been answered:

 We have a Hippiestation folder and all code in that folder overrides the /tg/ folder correct?

So let's say six months from now, we make minor changes to a great deal of things collectively that have to be made in large files. Now /tg/ does a major feature that also effects these large files that we have HippieStation versions of. So now in order to port that major feature we have to manually port it right? Because the changes made by the MIRROR PR won't actually affect us because we are already overriding the base code? So won't this sort of kill the mirror system given enough time?

**Comment by Uqualm** [comment]
Yes unquestionably what you told me was wrong.

**Comment by Uqualm** [comment]
Yes okay. This confirms it.  My above comment stands.

**Comment by Uqualm** [comment]
Alright this should work.

**Comment by tortellinitony** [comment]
Test it in game, please.

**Comment by Uqualm** [comment]
https://my.mixtape.moe/pugskf.mp4

**Pull request merged**
