### PR TITLE
removes shitty gamemode that requires high rp and trusts the crew to not self-antag with spells

### PR DESCRIPTION
**Pull request by Spacedong**
:cl: Spacedong
del: Removed the devil gamemode from the rotation.
/:cl:

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
Just sayin' merging this won't do shit because the config on the server is not the same as the config settings on github.

**Comment by Spacedong** [comment]
fuc

**Comment by McBawbaggings** [comment]
I can't modify the config settings to remove devil itself atm, I would have done it in the config update PR if possible.

**Comment by Spacedong** [comment]
lets just delete devil.dm

**Comment by MoreRobustThanYou** [comment]
take it up with admiral

**Comment by dreamcrab** [comment]
please do not take it up with hippie, tell a headmin

we will have access once the transfer is complete

**Comment by MoreRobustThanYou** [comment]
@dreamcrab oh ok. i edited my comment.

**Comment by PopNotes** [comment]
take it up with me fucko

**Pull request closed without merging**
