### PR TITLE
changed vendor sprites to be better

### PR DESCRIPTION
**Pull request by Spacedong**
old shitty sprites with barely any shading and they're too short: 

https://vgy.me/b7vDz9.png

new sprites:

https://vgy.me/z5Rp2x.png

### CODE REVIEW

**Comment by tortellinitony** [comment]
You did this wrong and I don't like the old sprites, too.

**Comment by Spacedong** [comment]
its not done wrong

**Comment by Spacedong** [comment]
fixing this hold on

**Comment by tortellinitony** [comment]
Here's what you will have to change:
a) The vending machines are in hippiestation/code/game/machinery/vending_types.dm
b) You will have to change the random machines to only pick the default vending machine.
c) There is a random for soda and snacks, maybe some others.

**Comment by Spacedong** [comment]
bawg is gonna put up a PR with that shit tomorrow because i couldnt figure it out but yeah I know

**Comment by tortellinitony** [comment]
I'll close this if mcbaw will make one tomorrow

**Pull request closed without merging**
