### PR TITLE
comments out blastco

### PR DESCRIPTION
**Pull request by k-k-karma**
:cl: karma
del: Removes BlastCo temporarily
/:cl:

[why]: newbie bait as it's not in the map atm. if it bugs out it can fuck over a warops round.

### CODE REVIEW

**Comment by danhibiki** [comment]
This should get some serious review if it can bork nukeops rounds.

**Comment by yskefunky** [comment]
yeah but blastco shit is fun af to spawn, just fix centcomm side by bringing back the old centcomm -1

**Comment by k-k-karma** [comment]
i am not maintaining centcomn

**Comment by Pyko1** [comment]
I recall it was decided long, long time ago.
That blasco shit should be recreated as a template.
that gets loaded on purchase to avoid abuse, and to allow more gimmick packs.

**Comment by bardofrage** [comment]
+1

**Comment by t-f-w** [comment]
+1

**Comment by danhibiki** [comment]
+2 approved needs review

**Comment by GuyonBroadway** [comment]
While I usually dislike commenting this out this is temporary sooo......

**Pull request merged**
