### PR TITLE
Brings back Dilbert 3

### PR DESCRIPTION
**Pull request by Uqualm**
Dilbert 3 is the classic SS13 lobby theme used for years on multiple servers. It's one of /tg/'s lobby themes. Because you only replaced 3/4 titles you left one /tg/ theme left. It was pretty shitty and I'm pretty sure we all know this one so here you go, I changed it.

### CODE REVIEW

**Comment by Uqualm** [comment]
https://www.youtube.com/watch?v=kGRCamvowcw

**Comment by McBawbaggings** [comment]
Just add it as a new file in our hippie folder.
Modify https://github.com/HippieStation/HippieStation/blob/master/strings/round_start_sounds.txt to add this new sound.

**Comment by Uqualm** [comment]
I simply replaced the "title4.ogg" which is another /tg/ lobby theme, with the new ogg. That way you still have 4 lobby themes and you get rid of the bad one.

**Comment by McBawbaggings** [comment]
Lobby music is probably more jamie's call. I mean I do like dilbert 3 though.

**Comment by GuyonBroadway** [comment]
I think that having the clown.wmv remix is more our style... and we already got that.

[https://www.youtube.com/watch?v=d2xkpz-26jM](url)

Although if we're open to discussing SS13 music, I really really have a soft spot for Musique d'intro n°2 [https://www.youtube.com/watch?v=pInBXkt3jvQ](url)

**Comment by McBawbaggings** [comment]
Honestly I think songs should be tied to lobbyscreens since some suit them more than others.

**Comment by cacogen** [comment]
it's from the gameboy robocop pleb

**Pull request merged**
