### PR TITLE
Mapfix + Adds resource storage

### PR DESCRIPTION
**Pull request by Pyko1**
:cl: Pyko
fix: fixed the broken mapchange mirrors
/:cl:

### CODE REVIEW

**Comment by Pyko1** [comment]
prolly needs some other files as well to be added

**Comment by praisenarsie** [comment]
o       wo what's this

**Comment by Pyko1** [comment]
its a file changed by https://github.com/HippieStation/HippieStation/pull/8347

**Comment by praisenarsie** [comment]
This PR adds resource storage with no more broken maps.
:crossed_fingers:

**Pull request merged**
