### PR TITLE
Buff devil

### PR DESCRIPTION
**Pull request by DON-KARMA**
Changelog
:cl:
balance: Devils now ascend at 8 souls and become a true devil at 5, from 12 and 7 respectively.
balance: Devils can no longer have cremation as one of their banishment routines.
balance: Devils also now take shorter to ascend.
/:cl:

devils are way too rare on hippie and i'd like to see them played more and I have _never_ seen an ascended devil on hippie at all

### CODE REVIEW

**Comment by DON-KARMA** [comment]
> no attempt at even doing a `// hippie -- buff devil`

that's ok, the mirror bot is off forever right

**Comment by steamp0rt** [comment]
it has been for a while.

we still modularize, though.

**Comment by Manly-Dwarf** [comment]
why you makin balance PRs bro wtf

**Comment by AnthonyJNgo** [comment]
+1, also mirror bot off forever, hippie we in this

**Comment by DON-KARMA** [comment]
i'm not fucking modularizing this we have the mirror bot off for a reason

**Comment by cris5311** [comment]
+1

**Comment by Maroonenahmoron** [comment]
+1, only seen an ascended devil once here. With our server numbers, this is much needed.

**Comment by Majick1** [comment]
Devil is more a roleplay boss which is probably why they have a harder time capping, they do need more playtime though, +1

**Pull request merged**
