### PR TITLE
Seclites are now robust as advertised.

### PR DESCRIPTION
**Pull request by PopNotes**
:cl: PopNotes
balance: Seclites are now robust as advertised.
/:cl:

### CODE REVIEW

**Comment by McBawbaggings** [comment]
i mean sure?
like, i always put the sec light on me gun though

**Comment by GuyonBroadway** [comment]
Now officer chad needs even less extra gear to dunk punks.

**Comment by PopNotes** [comment]
Harmbaton is an outdated meme, harmlite is the new kazoo

**Comment by GuyonBroadway** [comment]
I almost think we should add a goon esque system where if you harmbaton a nerd you hit yourself and get stunned.

Anywho needs one more headmin +1 before I can hit the go button.

**Comment by bardofrage** [comment]
Plus one

**Pull request merged**
