### PR TITLE
Cap's sword now dismembers more at the cost of damage

### PR DESCRIPTION
**Pull request by k-k-karma**
:cl: karma
balance: Cap's sword now dismembers more at the cost of damage
/:cl:

[why]: The whole point of it is  to dismember and it's a bit poor at that

### CODE REVIEW

**Comment by Kawaii-Big-Boss** [comment]
hell ye

**Comment by yoyobatty** [comment]
Maybe make it 12

**Comment by Lxtoofonea** [comment]
sure +1

**Comment by GuyonBroadway** [comment]
Remember that any weapon with a dismember chance when applied to torso will disembowl the dude killing them instantly if it rolls that chance.

**Comment by k-k-karma** [comment]
yeah disembowling is ridiculous i forgot, they do have better weapons than this though but i'll see what i can do

**Comment by yskefunky** [comment]
yeah uh not 100% on this, the reason it got nerfed in the first place was because of the fucking one hit murder chains you could do -1

**Comment by yoyobatty** [comment]
Please note I've already buffed the sabre by decreasing the attack delay to 0.6s from 0.8s, take that into account with this pr.

**Comment by Eagle-Eyess** [comment]
it was nerfed because of dismemeber chance. I don’t think it is a good idea to give that back. -1 I thought the increase attack speed was pretty good anyway...

**Comment by t-f-w** [comment]
yeah dismemberment can get pretty whack. feel like the attack speed buff is better suited. -1

**Comment by danhibiki** [comment]
Denied -2 headmin votes

**Comment by GuyonBroadway** [comment]
Negative two my good man, sorry but if you wanna take another **MEATY WHACK** at this, ask a headmin.

**Pull request closed without merging**
