### PR TITLE
Hippiestation map update

### PR DESCRIPTION
**Pull request by Pyko1**
Pasted (hopefully) all of our changes in to current box map to update/fix things all around the station.

### CODE REVIEW

**Comment by Pyko1** [comment]
Things that I at least did paste.

- Chapel
- chapel maint
- engine
- ai satellite
- maint bar
- forge
- cloning
- brig disposals
- gravity generator
- clown/mime office
- vault
- maint chem
- potted plants

**Comment by Pyko1** [comment]
- Cryo
- Chemistry
- Head privacy shutters

**Comment by praisenarsie** [comment]
yeet

**Comment by Pyko1** [comment]
@MapDiffBot

**Pull request merged**
