### PR TITLE
Removes the smoke machine from the chem lab

### PR DESCRIPTION
**Pull request by Spacedong**
fuck you TG ill fucking cut you up admins can still spawn it in tho
:cl: Spacedong
del: Removed the smoke machine from the chem lab.
/:cl:

[why]: # its fucking
 # STUPID

### CODE REVIEW

**Comment by PopNotes** [comment]
fuck off

**Comment by praisenarsie** [comment]
good pr

**Comment by Spacedong** [comment]
by this point I'm just thinking that 
# PopNotes

will just deny any PR made by me because its me rather than that its a good change, the smoke machine is just an unbalanced piece of shit and until smoke code is completely revised chemists should rely on grenades to deliver their payload, at least grenades cost wires, metal, beakers, and timers

**Comment by MoreRobustThanYou** [comment]
no, keep the meme machine

**Comment by PopNotes** [comment]
no your PRs are all fucking awful

**Comment by Spacedong** [comment]
you dont need to bea fucking intellectual 2 see that the smoke machine is horribly fucking unbalanced and shit

**Comment by banthebantz** [comment]
I'm nerfing it in my other PR as I feel it's the chempiles it produces that are the main issue.

**Comment by Spacedong** [comment]
no, the chempiles dont even matter, smoke code itself is fucky and awful, and the fact that it makes so much is autistic, why do chemists need an overpowered portable machine that makes chemicals in a fuckhuge area? it makes grenades useless, and grenades actually cost time and effort to make

**Comment by tortellinitony** [comment]
I think a huge problem with this is that the **FULLY ASSEMBLED MACHINE** is available at roundstart

**Comment by tortellinitony** [comment]
Make it so that you can only get the board.

**Comment by Chnkr** [comment]
This PR is awful, there is no additional lag that is introduced by this machine

**Comment by Spacedong** [comment]
lag wasn't the fucking point did you even read my reasons, anyways this can be closed because of https://github.com/HippieStation/HippieStation/pull/4370

**Pull request closed without merging**
