### PR TITLE
Nerfs the fuck out of radiation

### PR DESCRIPTION
**Pull request by KingTerrytheTerrible**
So one fuckwit making tritium doesn't make your game unplayable if there's nobody willing to help you; antags will actually have to try to ruin the entire station with fusion
## Changelog
:cl:

balance: nerfs rads

/:cl:

### CODE REVIEW

**Comment by carlopault** [comment]
What exactly is changed with radiation

**Comment by karmaisblackandbluepilled** [comment]
-3 rads are extremely based and extremely hard to make

**Comment by KingTerrytheTerrible** [comment]
> 
> 
> -3 rads are extremely based and extremely hard to make

50/50 oxygen and plasma generates about 10k rads, enough to cripple someone for the entire game

**Comment by KingTerrytheTerrible** [comment]
Fusion still shits on the station and antags cant just abuse rad hammers to instakill anymore

**Comment by KingTerrytheTerrible** [comment]
btw check out my event gamemode pr

**Comment by FantasticFwoosh** [comment]
-2 This is bad, and poorly informed. Obviously you don't know how to decontaminate their suit or self medicate, in the worst cases you just get cloned and ask a borg to incinerate your old body/help hook you up to a IV with iodine when in a sterile enviroment.

If you're nerfing all radiation you might want to question why a player can access 10k radiation in the first place (legitimate uses for SM rad collectors for instance).

**Comment by Neo1w** [comment]
i died pls nerf

**Comment by mkikt4743** [comment]
I have never seen an engineer decontaminate his suit, nigga just showers and then walks around like a fucking dirty bomb

**Comment by KingTerrytheTerrible** [comment]
> 
> 
> -2 This is bad, and poorly informed. Obviously you don't know how to decontaminate your protective suit (you SHOULD be wearing in the presence of radiation via gieger scale) or self medicate/seek treatment, in the worst cases you just get cloned and ask a borg to incinerate your old body/help hook you up to a IV with iodine when in a sterile enviroment.
> 
> If you're nerfing all radiation you might want to question why a player can access 10k radiation in the first place (legitimate uses for SM rad collectors for instance).

picture this: genetics is gone
there are no doctors because we're constantyl fucking 14 pop now

you get hit by rads on accident possibly with a incinerator gone wrong and you develop the teleporting mutations
this means you're in constant stunlock from the throwing up from the rads AND the mutation and when you're not you're slow as fuck because you're hungry and dying from toxins. shower doesnt help because it doesnt cleanse you and you cant get into chem to make antitoxin

**Comment by yoyobatty** [comment]
What a lazy edit, you just added 0's to everything, that just makes rads 10x safer and less dangerous for all aspects, doubling or every 50% increase would be more appropriate. Also, try wearing radiation suits or making showers more effective at ridding rads.

**Comment by Punkinguy** [comment]
-1

**Comment by Neo1w** [comment]
I'm going to close because nobody here but you wants it

**Comment by KingTerrytheTerrible** [comment]
who made this fucking retard 🇧🇷 maintainer

**Pull request closed without merging**
