### PR TITLE
Enable idling on the server

### PR DESCRIPTION
**Pull request by DON-KARMA**
Make sure you all stay connected so we can get to the top of the hub all the time! #highpop

### CODE REVIEW

**Comment by diegoxt45** [comment]
you'l just fill the server with bots won't you

**Comment by DON-KARMA** [comment]
i can make bots reconnect, i cant make humans reconnect

**Comment by steamp0rt** [comment]
```
code/controllers/subsystem/server_maint.dm:54:warning: round_started: variable defined but not used
code/controllers/subsystem/server_maint.dm:57:warning: afk_period: variable defined but not used
```

**Comment by Manly-Dwarf** [comment]
no bro

**Pull request closed without merging**
