### PR TITLE
Coding-enforced literacy

### PR DESCRIPTION
**Pull request by PopNotes**
:cl: PopNotes
add: French colors will no longer be tolerated. (Saying 'rouge' gives you brain damage and causes an unfunny sound effect to play every time you do it.)
/:cl:

### CODE REVIEW

**Comment by 2Dollarbill** [comment]
+1 from me, this is absolutely genius.

**Comment by DinduStuffin** [comment]
+1
This is why we love you popnotes

**Comment by PopNotes** [comment]
I changed my mind, it's 60 instead

**Comment by t-f-w** [comment]
+1
we need the same for other french colors ie bleu, brun, noir, etc.

**Comment by GuyonBroadway** [comment]
that's a good code review and a +2.

Merging.

**Comment by Mlgdatboiwew** [comment]
oh god why

**Comment by McBawbaggings** [comment]
wow

**Comment by GuyonBroadway** [comment]
It did get itself a +2 but feel free to set up a revert if you so desire.

**Comment by McBawbaggings** [comment]
nah, it's cool, just surprised people voted it up so quickly

**Pull request merged**
