### PR TITLE
Removes reagent bullshittery from circutis

### PR DESCRIPTION
**Pull request by k-k-karma**
:cl: karma
del: Removes reagents from circuits
/:cl:

[why]:  server-crashing methsmoke, instakilling water/potassium suicide drones, etc

### CODE REVIEW

**Comment by Carbonhell** [comment]
Isn't the problem chem tiles,and not this

**Comment by Carbonhell** [comment]
Asked the circuit discord people to discuss here, please do not merge till a proper discussion is made ay

**Comment by Lxtoofonea** [comment]
+1 they need a nerf

**Comment by Lxtoofonea** [comment]
i resend my +1, going to wait for chuckster/lyla's opinion

**Comment by steamp0rt** [comment]
i ded plz nerf

**Comment by Hate9** [comment]
It looks like it's pretty much solely a chemistry problem (exploding smoke is obviously not supposed to happen), so I don't see how circuitry having chemistry would in any way be the problem.

-1

**Comment by k-k-karma** [comment]
THATS NOT THE FUCKING POINT

**Comment by Hate9** [comment]
@k-k-karma Then please explain the fucking point.

**Comment by k-k-karma** [comment]
people are instakilling with it nigger

**Comment by Hate9** [comment]
@k-k-karma 
Please do try to keep your language civil.
If a chemical combination can instakill someone, I feel like that's the problem, not that a circuit can use the chemicals.
Also, removing all ability to work with chemicals is pretty obviously going overboard, so it sort of looks like you're just throwing a fit because someone killed you.

**Comment by AnthonyJNgo** [comment]
@Hate9 anyone that is knowledgable on circuits can build suicide bomber drones (water + potassium), or use circuits that will mass produce methsmoke that spams logs and crashes the servers. Removing reagents from circuits takes care of those issues. Chemistry is fine. Methsmoke is fine. Water + Potassium is fine. Being able to make thousands of instances of methsmoke with little to no effort after initial setup is gamebreaking. Does that clear things up a bit?

**Comment by k-k-karma** [comment]
@Hate9 op bullshit #1 ( circuits ) + op bullshit #2 (chemistry) = extreme op instakilling servercrashing bullshit

**Comment by AnthonyJNgo** [comment]
I'm against removing it entirely unless karma can put out a good argument to sway everyone. Nearly every job has the potential to be "OP". Releasing tesla, blowing sm, sing as engineer, releasing virus as virologist, chemistry shenanigans, superpowers as genetics, the slime extracts as xenobio, in karmas case tritium bombs that are able to COMPLETELY wipe out the station from the Z level, and so on.

**Comment by Hate9** [comment]
@AnthonyJNgo Oh look, someone willing to calmly discuss actual issues!
Alright, so first of all, last I heard, most people consider methsmoke an issue in and of itself, so I disagree that it's not a problem to begin with.
On the other hand, I agree that the potassium water suicide drones are an actual issue.

**Comment by k-k-karma** [comment]
roundstart aimbotting instant kills with no forewarning isnt a good enough reason

**Comment by k-k-karma** [comment]
> I'm against removing it entirely unless karma can put out a good argument to sway everyone. Nearly every job has the potential to be "OP". Releasing tesla, blowing sm, sing as engineer, releasing virus as virologist, chemistry shenanigans, superpowers as genetics, the slime extracts as xenobio, in karmas case tritium bombs that are able to COMPLETELY wipe out the station from the Z level, and so on.

YEAH MATE NONE OF THOSE INSTANTLY KILL YOUR TARGET AUTONOMOSLY THOUGH DO THEY

**Comment by Hate9** [comment]
I don't know, removing the entire station seems like a pretty effective way to instantly kill your target.

**Comment by Hate9** [comment]
And, more importantly, it sounds like a bigger problem.

**Comment by k-k-karma** [comment]
i was the one doing that and i needed to tc trade for no bomb cap so it requires admin intervention

**Comment by k-k-karma** [comment]
THERES A REASON WE HAVE A BOMB CAP

**Comment by Hate9** [comment]
I mean, we could just straight up cap the damage a circuit can do. That would solve the problem and some future ones as well.
I'm all for circuits being able to damage people, but instakilling is a legitimate concern.

**Comment by k-k-karma** [comment]
YOU CANT CAP THAT

**Comment by Hate9** [comment]
Are you kidding? Of course you can.

**Comment by AnthonyJNgo** [comment]
@Hate9 Methsmoke is kind of an issue, but I wouldn't go so far as to say it's gamebreaking per se. But when you combine it with circuits, you're able to release it way way faster. Pulling this example from thin air but imagine a weapon that can do 20 damage per hit. Lets say a player has 100 health. That weapon is pretty tough, can kill in 5 hits, maybe even considered overpowered. Circuits amplify that effect, so now it does 10x damage. That weapon now does 200 damage every hit, effectively gibbing a player by touching them. That's gamebreaking.

**Comment by k-k-karma** [comment]
DO IT THEN CUNT

**Comment by Hate9** [comment]
@k-k-karma, firstly, once again, please be civil.
Secondly, I'd be happy to put in the work to make an actual solution, but I'd rather discuss alternatives with other players first.

After all, unlike your solution, mine would require actual work.

**Comment by k-k-karma** [comment]
yeah you tell me how to solve instant killing bots with water potassium that aimbot then

**Comment by Hate9** [comment]
@k-k-karma I literally just did, and you decided that my solution was impossible without giving a single reason why.

**Comment by k-k-karma** [comment]
reagent explosions arent even capped for starters

**Comment by Hate9** [comment]
I think you'll find that "aren't" and "can't be" are different.

**Comment by k-k-karma** [comment]
go ahead and do it then nothing's stopping you mate

**Comment by Hate9** [comment]
@k-k-karma
> […]I'd be happy to put in the work to make an actual solution, but I'd rather discuss alternatives with other players first.
> 
> After all, unlike your solution, mine would require actual work.

**Comment by k-k-karma** [comment]
start discussing then

**Comment by k-k-karma** [comment]
also what's your discord

**Comment by AnthonyJNgo** [comment]
@k-k-karma what about not making certain mixtures combinable in circuits?

**Comment by Hate9** [comment]
Honestly, I'd rather not have you messaging me all day, so I'm going to avoid giving you my information.
If you want to talk to me on Discord, you can join the Circuitry Discord.

**Comment by AnthonyJNgo** [comment]
Just add a check and if there's a chemical reaction that is blacklisted then the machine just malfunctions, and displays some kind of message like, "Circuitmachine begins to overheat, shudders heavily, then powers off."

**Comment by k-k-karma** [comment]
oh of course you're on the circuitry discord which is why you dont want it removed

**Comment by zamolxius** [comment]
Chill

**Comment by Hate9** [comment]
Right?

**Comment by k-k-karma** [comment]
@AnthonyJNgo not sure if that's possible and even then people would find a way. until reagents are rebalanced it's best that we just remove them from circuits for now

**Comment by Hate9** [comment]
@AnthonyJNgo I was considering that, but I feel like capping damage is a more extensible solution, and would solve any other instakill issues later.

**Comment by WarRage333** [comment]
Jesus christ calm down, blacklist certain mixes in instead of removing all

**Comment by k-k-karma** [comment]
@Hate9 how the fuck would you go about capping damage from bombs in circuits only

**Comment by Hate9** [comment]
@k-k-karma Even if that were a good option (which it isn't), deleting the files is the wrong way to go about it.
You should either remove the reference to the circuitry chemistry file from the .dme, or at least just comment out the files.
Temporary fixes are supposed to be temporary.

**Comment by k-k-karma** [comment]
it's git, we can revert commits

**Comment by AnthonyJNgo** [comment]
@Hate9 capping damage is a good idea but honestly I have no idea on how to do that and don't have the slightest clue on where to start. Blacklisting certain mixtures would be easy though. Hell, for rp value you could even say the installed nanotrasen softeare detects the mixture and deems it too dangerous or whatever, then shuts down the circuit remotely.

**Comment by Hate9** [comment]
@k-k-karma I would add something in the explosion proc(s) to check what type of container the chemicals were mixed in, and if it was a circuit, I'd cap the damage.

**Comment by Hate9** [comment]
@AnthonyJNgo To be fair, that is a definite benefit to your solution.

**Comment by zamolxius** [comment]
Hey man,  come to the discord,  theres more discussion there and it's realtime too @hate9
Discord: https://discord.gg/JMuzYhV

**Comment by Hate9** [comment]
Sure, sounds good to me.

**Comment by steamp0rt** [comment]
> We are working on nerfing printing circuits

Please tell me i'll still be able to use wiress13.cf, else circuits will be no fun since the round will be over once I get one to work

**Comment by steamp0rt** [comment]
but yeah, it's proven @k-k-karma is just plain stupid and has an ided-fueled hate boner

**Comment by Memendia** [comment]
I must think too highly of @k-k-karma as reading all this I was thinking there was actual coding done... not just deleting a file and un-ticking something.

If you are going to remove something that a large group of players enjoy you) you have to put some effort into it.

_Ya also need to learn how to be calm._

**Comment by k-k-karma** [comment]
WHY DO I HAVE CONFLICT SIM FUCKING DLEETING THE IFLE

**Comment by Carbonhell** [comment]
-1. Removing the whole category is a lazy approach to the problem. Either fix the issue chemwise or try to keep as many circuits as possible, and tweak them, remove only if nothing else can be done (for example, the thrower should be removed)

**Comment by Jujumatic** [comment]
the code is fighting back

also this change is gay

**Comment by yoyobatty** [comment]
Too much controvery and -1's. Fundamental issues relating to this PR have mostly been fixed too.

**Pull request closed without merging**
