### PR TITLE
NE maint fixes

### PR DESCRIPTION
**Pull request by Pyko1**
:cl: Pyko
add: Added missing NE maintenance room lamps, and a Sooka Blyat - Missionk Akkomblished!!-buttonk in
russian room
fix: fixed wrong type of foam darts in maint
/:cl:
fixes the foam darts beign projectiles, there is now 4 normal foam darts
and 1 riot foamdart.
Adds couple lamps to ported areas that were lacking em.
Party button, I mean Sooka Blyat - Missionk Akkomblished!!-buttonk in
russian room.

Fixes: https://github.com/HippieStation/HippieStation/issues/2964

### CODE REVIEW

**Comment by Pyko1** [comment]
party button is technically a feature the added lamps used to be somewhere around there.

The 1 riotdart might or might not be a feature, i recall there used to be like 5 of them at some point.

**Comment by McBawbaggings** [comment]
bad changelog
please actually put meaningful changes in

**Comment by McBawbaggings** [comment]
cheers

**Comment by Pyko1** [comment]
fixed the changelog

**Comment by tortellinitony** [comment]
Pics please

**Comment by Pyko1** [comment]
Is pics really needed its literally total of 6 lamps that were forgotten when i remade the hippie maint rooms, and a party alarm button on a wall in the ruskie room.

**Comment by Pyko1** [comment]
oh 7 since the chaplains booze stash also missed lamp

**Pull request merged**
