### PR TITLE
Revert "Scientists now randomly burst into flames"

### PR DESCRIPTION
**Pull request by KingTerrytheTerrible**
Reverts HippieStation/HippieStation#12272

Literally no point, only disrupts noobs who dont know how to use fire extinguishers. Since when has engi given a rats fucking ass about science? it's just annoyign for people who cant avoid it and for other people who set people on fire with it

### CODE REVIEW

**Comment by zamolxius** [comment]
hurrr durr noooooo my science power and independence is oozing away noooooooo

**Comment by TrickyDickRichard** [comment]
-1 owned nerd

**Comment by KingTerrytheTerrible** [comment]
i don't play scientist i main clown and it's fucking ANNOYING WHEN I CANT RUN AWAY IN TIME

**Comment by enthethan** [comment]
Tbh this only really affects unrobust retards who don't know how to use an extinguishet

**Comment by mkikt4743** [comment]
-1 is a fun mechanic, also nerfs sci

**Comment by danxnader** [comment]
-1 fun

**Comment by xTrainx** [comment]
+1 It doesn’t even affect scientist because they're are 2 tiles you can use the computer on without catching la fire at all so it mostly just affect everyone else who don’t usually play science

Next time just rig end to blow up as soon as someone uses it

**Comment by MrEpicSax** [comment]
-1 I like it. It's fun and spices things up a bit.

**Comment by cris5311** [comment]
-1
reasons listed in the pr for the fire thing

**Pull request closed without merging**
