### PR TITLE
The Butt Update part 2: Fartvengeance

### PR DESCRIPTION
**Pull request by PopNotes**
🆑 PopNotes
add: A bunch more fart messages
soundadd: Two shiny new fartsounds
/🆑

### CODE REVIEW

**Comment by banthebantz** [comment]
BRAAAAAAAAAAAP

**Comment by PopNotes** [comment]
why the hell is this a fail

**Comment by FuryMcFlurry** [comment]
Im glancing over it. could it be because of how you ordered your array's? I could be completely of the mark here.

**Comment by PopNotes** [comment]
I THINK I figured it out.

**Pull request merged**
