### PR TITLE
A very serious balance change

### PR DESCRIPTION
**Pull request by PopNotes**
:cl: PopNotes
balance: Donuts no longer contain nutriment. Eat real food, you fat bastards.
/:cl:

### CODE REVIEW

**Comment by banthebantz** [comment]
🤔

**Comment by MoreRobustThanYou** [comment]
NO NO NO NONO NO NO NONO NO NO NONO NO NO NONO NO NO NONO NO NO NONO NO NO NONO NO NO NONO NO NO NO

**Comment by JamieH** [comment]
I'm with Amari on this one

**Comment by zamolxius** [comment]
huh,  it would actualy make people actually play chef,  and actually make food.  1+ from this headmin of brappiestation

**Comment by McBawbaggings** [comment]
no

**Comment by tortellinitony** [comment]
there is a reason that every department gets donuts

**Comment by PopNotes** [comment]
Sugar counts as a little bit of nutriment by itself, this just means you can no longer completely ignore the chef entirely by carrying around a box of donuts. :^)

**Pull request closed without merging**
