### PR TITLE
REMOVES FREE NO DOWNSIDE ADRENALS FROM R&D

### PR DESCRIPTION
**Pull request by k-k-karma**
:cl: karma
del: removes adrenal nanites
/:cl:

[why]: they're antistuns for free aside R&D points

### CODE REVIEW

**Comment by steamp0rt** [comment]
Did you forget that just HAVING nanites is pretty easy for an antag to fuck you over with?... 5 seconds after I told you?

And you say "NO DOWNSIDE". Pfft. Ling adrenals poison you, stimpack costs TC, nanites will eat you from the inside out if EMPed, or traitors can simple upload insta-splode or mind control nanite programs to the cloud backup?

**Comment by k-k-karma** [comment]
you're talking about downsides of NANITES not the nanite adrenals, let me explain
1) nanites will deal random damage (usually in the 0.5) range and nto work if emped, but the cloud resets this every 30 seconds.
2) literally no traitor does this at all and even then it's trivial just to get the ai to turn the cloud off if you notice insta-explode which isnt that instant at all

**Comment by steamp0rt** [comment]
Either way, these have been in for a while now... Have that causes balance issues? I don't think so.

Also, as you said, nanites in general are dangerous. But if the AI turns the cloud off, it won't sync... But if the traitor is smart, they'll cut the cams, upload Relay + bad nanites, grab the remote, wait about a minute, and splode everything with the remote.

**Comment by k-k-karma** [comment]
they do cause balance issues when they're used but nobody uses them because they're dumb
and i have never eve rseen a traitor fuck with nanites

**Comment by steamp0rt** [comment]
do you not know about the time I uploaded boom boom nanites as a non-antag, for a round-end surprise... then I dropped the remote control, and the clown detonated them?

some PSAs in OOC may change that fact, karma

**Comment by k-k-karma** [comment]
that sounds suspiciously like self-antag to me...........................

**Comment by steamp0rt** [comment]
@k-k-karma It wasn't, since I wasn't going to activate them til the round had ended. Like having a maxcap on the shuttle.

But the clown DID get banned for pressing the (clearly labeled) explosion button.

**Comment by steamp0rt** [comment]
lol on discord: karma thinks i purposefully dropped the remote.

**Comment by Kawaii-Big-Boss** [comment]
Antistuns were collectively agreed to be removed.
There's no point in arguing to keep them around considering literally every headmin and maintainer thinks they suck, and I think they suck.

**Comment by steamp0rt** [comment]
i like them



also nerf meth pills in teeth when?!?!?!?!!?

**Comment by k-k-karma** [comment]
you do realize meth has downsides and doesnt give you traitor stims?

**Comment by Kawaii-Big-Boss** [comment]
>I like them

this is why we all question your design
picardia2

**Comment by steamp0rt** [comment]
@k-k-karma Only downside is overdose and brain damage. First of which can be countered by simply not chugging it, the latter can be countered by making M&Ms -- meth n' mannitol.

**Comment by k-k-karma** [comment]
then you wouldn't mind me removing  adrenal nanites and just use M&Ms instead

**Comment by steamp0rt** [comment]
yeah but I can *wink to activate adrenal nanites

**Comment by k-k-karma** [comment]
fine i'll nerf meth too

**Comment by steamp0rt** [comment]
don't do it faggot. don't do it until swing-combat is in.

**Comment by k-k-karma** [comment]
then shut up and let htis be merged or i will go on an antistun removal rampage

**Comment by zamolxius** [comment]
meth also does eye damage

**Comment by steamp0rt** [comment]
@k-k-karma alternate suggestion: instead of removing, add downsides. improve don't remove

**Comment by steamp0rt** [comment]
@zamolxius MMOs - meth, mannitol, oculine

**Comment by k-k-karma** [comment]
no

**Comment by steamp0rt** [comment]
fag

**Comment by DaydreamPuppeh** [comment]
+1. The EMPs dont work for long and I only see this as powergamey

**Comment by HideAndSeekLOGIC** [comment]
ayy looks like my one comment on the massive nanite buff had some sort of an effect. Yeah, adrenaline nanites are a tad stronk as it stands. If not removing them, at least make them give the user more debuffs.

**Comment by Kawaii-Big-Boss** [comment]
If any antistuns are in the game, they're bad.
I said to add antistuns to ling as a joke related to how OP they were, and thankfully they were untested.
Any "antistun balance PR" will be followed with an "antistun removal PR" now that you've shown us that there are any surviving antistuns left in the game.
noantistuns

**Comment by steamp0rt** [comment]
Don't worry, I'll find more anti-stuns and keep them secret :)

**Comment by k-k-karma** [comment]
you do realize i'll be adjusting stun functions so negative values can't be used in AdjustKnockdown?

**Comment by DaydreamPuppeh** [comment]
This is what he will do because of his antagban

**Comment by k-k-karma** [comment]
he literally said that in the discord yeah

**Comment by steamp0rt** [comment]
@k-k-karma that'll unintentionally break shit probably.... like helping people up

**Comment by Kawaii-Big-Boss** [comment]
>Don't worry, I'll find more anti-stuns and keep them secret :)

And you wonder why nobody wants you in power as a maintainer or admin

**Comment by steamp0rt** [comment]
Why, because ya'll nerf anything robust due to jealousy?

**Comment by k-k-karma** [comment]
why's your maintainer app not closed

**Comment by Kawaii-Big-Boss** [comment]
Ask any coder or maintainer how bad antistuns got back in 2016-2017. They were removed due to them being extremely easy to make, extremely powerful, and if combined with certain armors such as HoS armor, made you pretty much invincible as you were constantly faster than everyone else, couldn't be stunned, and the side effects of "brain damage" were negligible.
They weren't "robust", they were the epitome of cheating yourself out of combat thanks to Stun Meta, and did nothing but help powergamers and validhunters who already had the entire armory in their backpack, riot shields, and other crap to abuse, to the point to where using antistuns was like a punchline.
So now that we have nanites that can heal you, and give you antistuns, and can be activated on emotes, they are already way too powerful and are basically just Science's own Virology, and Yobih has already shown us how cancerous Virology is so far.
If you're going to sit around and argue about antistuns being a worthwhile feature to the game, understand that items are not just used by themselves. Stuns would not be nearly as powerful without handcuffs, but together they are so powerful they outright define the game's combat at this point for non-antags. So, antistun's main weakness would be lethals, which suck thanks to chemistry (which is the exact thing antistuns are from, eh) also being incredibly powerful on top of a ton of other means to ensure you take very little damage as to circumvent the weaknesses of antistuns. This is what real powergaming is, it's not just "grabbing tasers", it's antistuns.
All of this made antistuns loathed on the server, especially thanks to how hard they were abused by Cappy and co, and got nerfed in a PR. Said PR completely failed to make antistuns balanced in any regard, since they might as well just be named "anti-combat" and eventually McBawbaggings put up a whole PR to remove antistuns as a whole. Said PR was ported over here when we rebased.

So, no, it's not out of "jealousy" or it being "robust", it's the exact opposite you big baby.

**Comment by danhibiki** [comment]
I'm flying particularly blind to nanites specifically, but I'm familiar with the hub-bub about anti-stuns. Removing this as an anti-stun isn't going to really solve the problem but just make people make use of anti-stuns in other mediums. Wouldn't it be better to just add more risk to using nanites in general?

**Comment by zamolxius** [comment]
good pR

**Comment by t-f-w** [comment]
+1

**Comment by yskefunky** [comment]
lol this shit fucking sucks get the fuck outta here steamport +1

**Pull request merged**
