### PR TITLE
Eliminates Sizzurp

### PR DESCRIPTION
**Pull request by PopNotes**
:cl: PopNotes
del: Lean is gone. Rest in purple.
/:cl:

### CODE REVIEW

**Comment by PopNotes** [comment]
lol wut

**Comment by JohnGinnane** [comment]
why

**Comment by dreamcrab** [comment]
nope

**Comment by Blute1** [comment]
no

**Comment by MoreRobustThanYou** [comment]
+1

**Comment by banthebantz** [comment]
Rename this PR or I will slay it where it stands

**Comment by MoreRobustThanYou** [comment]
FUCK LEAN FUCK LEAN FUCK LEAN FUCK LEAN FUCK LEAN FUCK LEAN FUCK LEAN FUCK LEAN FUCK LEAN FUCK LEAN FUCK LEAN FUCK LEAN FUCK LEAN  x 50000

**Comment by JohnGinnane** [comment]
image

image

**Comment by Blute1** [comment]
amari is not fit to be a maintainer after his constant spergouts

**Comment by GuyonBroadway** [comment]
Please stop fucking with the name or I will lock this till people decide to be sensible.

**Comment by MoreRobustThanYou** [comment]
@Blute1 @GuyonBroadway it's just that lean makes me SO. FUCKING. MAD. I HATE THE SHIT AND I WANT EVERY TRACE OF IT PURGED FROM THIS CODEBASE

**Comment by Arzion5** [comment]
Take the pilgrim's sandvich and you'll wake up in bed, going on with your life and forget that it ever happened. Take the lean, however, and I will show you how deep the rabbit hole goes

**Comment by McBawbaggings** [comment]
no

**Comment by MoreRobustThanYou** [comment]
confirmed: @McBawbaggings and @dreamcrab are against curing cancer!

**Comment by dreamcrab** [comment]
just gonna make sure you guys know that im saying no

no

-60

**Comment by Dudeinyourbackyard** [comment]
-500
continue anger

**Comment by Chnkr** [comment]
No

**Pull request closed without merging**
