### PR TITLE
fix hilberts hotel

### PR DESCRIPTION
**Pull request by k-k-karma**
aaaaaaa

### CODE REVIEW

**Comment by Kawaii-Big-Boss** [comment]
eeeeeee

**Comment by yskefunky** [comment]
hmm yess door i like +1

**Comment by yoyobatty** [comment]
What does this do?

**Comment by k-k-karma** [comment]
the bluespace floor tiles produce sparks when any atom go onto it, including sparks and they're bunched next to eachother. gregg blacklisted the ruin cos of this

**Pull request merged**
