### PR TITLE
circuitlab map fixes

### PR DESCRIPTION
**Pull request by Pyko1**
fixes https://github.com/HippieStation/HippieStation/issues/6227
Also fixes the circuitlab disposals not being connected.

cyberboss woz 'ere - praisenarsie

### CODE REVIEW

**Comment by tortellinitony** [comment]
pics

**Comment by Pyko1** [comment]
we really need the map diff bot. Ill get pics when i have time, not that there is much to see besides 3 lines of wire and couple pipes and 1 locker moved to north so its not inside a wall.

**Comment by Cyberboss** [comment]
Gotcha bae

**Comment by praisenarsie** [comment]
@Pyko1 cyberboss wanted to test mapdiffbot and hippie, so here you go. but looks like he left his mark on the pr body!!!1

**Comment by Pyko1** [comment]
nice bot, and there is your screens of visual changes

**Comment by JohnGinnane** [comment]
that's a really cool bot

**Pull request merged**
