### PR TITLE
Adds emagged circuits to the printer

### PR DESCRIPTION
**Pull request by karmaisblackandbluepilled**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
add: Added the shocker circuit, the thrower circuit and the weapon charger circuit, all locked behind emagging a circuit printer.
/:cl:

## About The Pull Request
I also nerfed the shocker by giving a 1 sec cooldown, 100 complexity and 10 size. God bless the USA.

## Why It's Good For The Game
is it?

### CODE REVIEW

**Comment by karmaisblackandbluepilled** [comment]
Discord_nk2pFKpDfU

**Comment by karmaisblackandbluepilled** [comment]
i had to paste the do_work and remove the weapon charger from the transmitter subtype because the do_work for transmitters checks specifically if the thing charged is a weapon and if it is, it stops it. I don't know how to remove that check *only* for the weapon charger

**Comment by carlopault** [comment]
what does a shocker circuit and thrower circuit do? Does science really need a buff

**Comment by karmaisblackandbluepilled** [comment]
the shocker shocks you
the thrower throws items
it's not a science buff if you need an emag for it

**Comment by carlopault** [comment]
+1  ok

**Comment by byandaccount** [comment]
+1 i miss shitty glass guns, they were the pneumatic cannons we deserved all along.

**Pull request closed without merging**
