### PR TITLE
Goof foam

### PR DESCRIPTION
**Pull request by k-k-karma**
:cl: Karma
add: GOOF FOAM IS BACK
balance: VENT CLOG WEIGHT INCREASED
balance: VENT CLOG REAGENT AMOUNT INCREASED
balance: VENT CLOG CAN NOW USE ALL REAGENTS
/:cl:

### CODE REVIEW

**Comment by Carbonhell** [comment]
are you CRAZY DUDE
NO

**Comment by k-k-karma** [comment]
yeah

**Comment by Jujumatic** [comment]
SPAM CATASTROPHIC BEFORE ITS TOO LATE

**Comment by Lxtoofonea** [comment]
are you sure about this.....?

**Comment by k-k-karma** [comment]
100%

**Comment by Lxtoofonea** [comment]
+1, for now

**Comment by TheMeatGod** [comment]
+1 F O A M

**Comment by uBadush** [comment]
merge just for curiosity if shit goes wrong revert

**Comment by Manly-Dwarf** [comment]
ARE YOU INSANE
AUGH NO

**Comment by DaydreamPuppeh** [comment]
+1

**Comment by t-f-w** [comment]
no -1

**Comment by DeltaFire15** [comment]
HECK NO -1

**Comment by k-k-karma** [comment]
your vote doesn't count; fuck off

**Comment by Carbonhell** [comment]
-1
Although i'd be up for testmerging it for a round and laugh at the chaos if it cannot be done with VV ingame

**Comment by k-k-karma** [comment]
ok i'll settle for that if i can remove the required players

**Comment by DaydreamPuppeh** [comment]
+1. But testmerge first

**Comment by CocaColaTastesGood** [comment]
-1, was test merged, the spawn chance seems increased for the vent clog event, causes chem-trails.Usually kills half of the crew, some times it kills most of the crew.Other times it makes everyone a catperson,lizard,moth,golem, or actually does something good.

**Comment by Reydane** [comment]
I actually played with this twice, it is absolute cancer, it breaks the flow of the round entirely, ruins peoples rounds at arrivals. -1

**Comment by k-k-karma** [comment]
ready to merge

**Comment by Reydane** [comment]
No

**Comment by TheMeatGod** [comment]
The flood lasts way too long

**Comment by Reydane** [comment]
Literally no one wants this

**Comment by mikolaj007** [comment]
-1

**Comment by k-k-karma** [comment]
+1

**Comment by TheMeatGod** [comment]
-1

**Comment by uBadush** [comment]
Maybe this should be admin only spawnable

**Comment by GuyonBroadway** [comment]
This shit can clog the supermatter and irrevocably break the darn thing even if you buiold a super safe setup.

**Comment by Jujumatic** [comment]
part of the feature, approved stamp!!

**Comment by Carbonhell** [comment]
This had enough time. Players don't like it,sorry man.
Gonna close it in a few hours.

**Comment by CocaColaTastesGood** [comment]
The idea itself wasn't too bad, but it's too chaotic.

**Comment by Jujumatic** [comment]
This would be cool if it was made adminspawn at least so we can have shitmins abuse this

**Comment by k-k-karma** [comment]
no; admins suck and it'll never get used

**Comment by uBadush** [comment]
Manly dward literally spams events like hell

**Comment by DaydreamPuppeh** [comment]
I would use this if I wanted to force a round end if it goes on for too long

**Comment by Reydane** [comment]
Yeah, that's the only time it should be used, but in it's current state its
a random event that ruins perfectly good rounds way too often

**Pull request closed without merging**
