### PR TITLE
Gender Reassignment Surgery

### PR DESCRIPTION
**Pull request by Uqualm**
Adds back gender reassingment surgery.

### CODE REVIEW

**Comment by Uqualm** [comment]
Yep. Fixing the priority ones first.

**Comment by Uqualm** [comment]
10:46:17 hippiestation.mdme:2027:error: unable to open "code/modules/surgery/gender_reassignment.dm".

Wow, what a descriptive error.

**Comment by JamieH** [comment]
@Uqualm you should include `hippiestation/code/modules/surgery/gender_reassignment.dm`

**Comment by Uqualm** [comment]
I did.

**Comment by Uqualm** [comment]
AHHHHH not sure how that happened. Well, I'll fix that. Not my lucky day today, many bugs.

**Comment by Uqualm** [comment]
Something is definitely messed up here. Going to try again on a new branch, think I fucked myself up.

**Pull request closed without merging**
