### PR TITLE
AT and mirror map fix

### PR DESCRIPTION
**Pull request by Pyko1**
added missing map changes from mirrors.

to cargo/circuitlab/techstorage/kitchen
Fixed some AT's around map

### CODE REVIEW

**Comment by Pyko1** [comment]
literal copypastes from box to hippie on unedited areas and couple aT fixes on top of that since people had been using airless palating in the station.

**Comment by Pyko1** [comment]
oh and some repathing that didint conflict for some reason

**Comment by GuyonBroadway** [comment]
did you add the games vendor to the library?

**Comment by Pyko1** [comment]
adding it

**Comment by Pyko1** [comment]
added

**Comment by GuyonBroadway** [comment]
Merging fix

**Pull request merged**
