### PR TITLE
removes VORE

### LINKED ISSUE #9603: vore is overpowered
permadeath, there's no way to get the person you vored out of your body while permadeath should be hard and challenging

### PR DESCRIPTION
**Pull request by k-k-karma**
:cl: karma
del: Removes VORE
/:cl:
Closes #9603

### CODE REVIEW

**Comment by Kawaii-Big-Boss** [comment]
excuse me what

**Comment by danhibiki** [comment]
You can eat monkeys if your fat. It’s a classic gag

**Comment by Kawaii-Big-Boss** [comment]
excuse me what

**Comment by danhibiki** [comment]
Grab monkey, punch it in your face, wait

**Comment by Kawaii-Big-Boss** [comment]
This isn't a classic joke, this was actually stealthily merged by a /tg/ coder who made the whole "pull/grab into one thing" PR.
I guess none of the other coders realized it.

**Comment by zamolxius** [comment]
wtf,  didnt we have fat people being able to eat monkeys before?

**Comment by danhibiki** [comment]
We most certainly had eating monkeys for years, if it was removed at one point is regardless that it’s a dated feature. I’d argue it was removed erroneously because this is something we had several years ago on this server

**Comment by k-k-karma** [comment]
are you literally defending human vore that got snuck in

**Comment by zamolxius** [comment]
it isnt vore,  vore is doing it for sexuals,  this is just an old meme,  not even related to "lol catgirls" fetish disguised as memes shit

**Comment by k-k-karma** [comment]
ok i guess doing it  without a sexual intent no longer makes it disgusting and not related to eating people as a sexual fetish FUCK OFF

**Comment by danhibiki** [comment]
You’ve never truly lived until you eat the bartenders monkey right in front of him

**Comment by k-k-karma** [comment]
i vored  the captain and some chef in one round, not only is it fucking gay it's ridiculously OP it's permadeath without a trace

**Comment by danhibiki** [comment]
So it’s grudge code then

**Comment by k-k-karma** [comment]
how is it fucking grudgecode i'm the one who fucking vored people

**Comment by zamolxius** [comment]
can you even vore HUMANS?

**Comment by zamolxius** [comment]
if its only monkeys just leave it in bro its cool, monkeys are valid anyways fuck them,  more reason for them to chimp out

**Comment by danhibiki** [comment]
Your doing it from a personal standpoint instead of actually weighing the process in, you don’t see how incredibly obscure this method of round removal is in comparison to other ways. You could more easily get access to the gibber than access to monkey someone

**Comment by k-k-karma** [comment]
no you can't vore humans but you can dna inject people to monkies which reverts them to human while in your stomach

**Comment by zamolxius** [comment]
so how does that matter
just make the monkeys gib when eaten then

**Comment by zamolxius** [comment]
so instead of deepthroating them you just chew them like a paper shredder

**Comment by k-k-karma** [comment]
that's an even worse fucking permadeath

**Comment by zamolxius** [comment]
nobody even clones monkeys most of the time,  you can also scan yourself beforehand

**Comment by bubberducky2** [comment]
lol i wanna vore some monkeys yummu yummu ; - ))))))))))))))))))))))))))))

**Comment by bubberducky2** [comment]
oooo my tummy rubbmly i wanna vore vore some monkey plssssssssssssssssssssssssssssss i wanna vore monkey plsssssssssss uwu uwu o i m sor unhgry i wanna fill my tummy with monkey bummy cUmmy ~~~~~~~~~~~~~~~~~~~

**Comment by k-k-karma** [comment]
what the fuck?

**Comment by McBawbaggings** [comment]
wasn't this code around for ages, before fatcode was broken

**Comment by k-k-karma** [comment]
it was snuck in 3 years ago

**Comment by k-k-karma** [comment]
turns out people like vore too much, also it was added before the tgstation github was made

**Pull request closed without merging**
