### PR TITLE
Revert "Removes antistun from hulk - keeps wall punching"

### PR DESCRIPTION
**Pull request by k-k-karma**
Reverts HippieStation/HippieStation#9697

### CODE REVIEW

**Comment by Manly-Dwarf** [comment]
karma was too lazy to actually add more to hulk so here we are
unfortunately this means unstunnable unkillable combos with hulk again but whatever

**Comment by k-k-karma** [comment]
that's it, yep

**Comment by Jujumatic** [comment]
Good luck getting hulk when hippie rounds last 2 seconds tho

**Comment by k-k-karma** [comment]
i'd be in favour of making them valid though

**Comment by WarRage333** [comment]
Hulk is so hard to get now dude, youre trading your ability to use most ranged weapons for wall bashing and not being able to be stunned (you still get slowed by stamina loss from disablers.)

And the its RNG gated behind genetcists i very rarely get it before minute 20 and you know what you need to do for 20 minutes is sit in one place, clicking buttons on a pc, you legit miss out the whole round if you try to get it.

**Comment by Jujumatic** [comment]
needs head votes

**Comment by Manly-Dwarf** [comment]
to spell it out for dumb coder boy who can't read, +1

**Comment by Lxtoofonea** [comment]
oh my god +1

**Pull request merged**
