### PR TITLE
Unleash the Griffons

### PR DESCRIPTION
**Pull request by Pyko1**
:cl: Pyko
add: Grief
del: Pacifism
del: Immersive sounds
/:cl:

### CODE REVIEW

**Comment by Carbonhell** [comment]
oh nvm, what about sounds tho? i'd like to keep them somehow ingame if possible...perhaps as a very low chance random event or wizard random event, would you be able to do it?

**Comment by Pyko1** [comment]
I think the sounds have to be removed and then properly implemented to co exist with normal sounds.

But yeah, I want to add some of the sounds permanently ingame.

**Comment by Carbonhell** [comment]
Aye, revert the sounds to the old one in this pr, then we can readd them in the proper way with future prs

**Comment by Pyko1** [comment]
and done

**Pull request merged**
