### PR TITLE
replaced those new topdown TG sprites and more

### PR DESCRIPTION
**Pull request by Blute1**
Replaced the computer sprites with ones that aren't topdown, replaced the vent and scrubber sprites with our old ones. Replaced the particle accelerator sprites as well. Overall this gives a more cartoony and fun feel than TG's current sprites.

:cl: Spacedong
tweak: Changed sprites, namely the particle accelerator, vents and scrubbers, and computers.
/:cl:

### CODE REVIEW

**Comment by Chnkr** [comment]
This does not work, and the /tg/ sprites are actually pretty decent.

**Comment by GuyonBroadway** [comment]
Ok so you never changed the icon vars on any of the machine syou are updooting so this will not work. 

Repeat after me.

**_ALWAYS COMPILE AND TEST!_**

**Comment by Blute1** [comment]
oh yeah here are the new spriites

PA: 



Computers and airvents/scrubbers pictured here in an old ass pic

**Comment by Blute1** [comment]
wait, icon vars need to reference hippie files? FUCK

**Comment by Blute1** [comment]
i will fix at once my lord

**Comment by GuyonBroadway** [comment]
Also the old PA is ugly as fugg and the new PA has a nice visual indication as to what power level its set to. The new computer sprites are directional (we just never remapped them to be the right direction)

**Comment by Blute1** [comment]
yeah but the new PA is ugly as shit and looks like its right from lifeweb, black/red/gold colorscheme on a space station, really nigger?

**Comment by Blute1** [comment]
the new computer sprites are top down which is shit

**Comment by Blute1** [comment]
we dont use top down perspective

**Comment by Chnkr** [comment]
@Blute1 The new sprites for the vents look pretty decent, and nobody seems to have complained yet.

**Comment by JohnGinnane** [comment]
I think they look like that because they can be rotated now

**Comment by Blute1** [comment]
the old sprites are superior, nobody has assed to complain

**Comment by Blute1** [comment]
nah, its because TG is leaniing towards goon top-down now

**Comment by Chnkr** [comment]
@JohnGinnane Correct, the new sprites can actually rotate 360 degrees and not look shit

**Comment by MoreRobustThanYou** [comment]
NO NO NO SPACEDONG NO @Blute1 STOP STANDING IN THE WAY OF PROGRESS!!!

**Comment by Blute1** [comment]
it is modular though

**Comment by Blute1** [comment]
oh fuck

**Comment by Blute1** [comment]
fuckfuckfucufuufufucifuufckk

**Pull request closed without merging**
