### PR TITLE
No Valentines day allowed

### PR DESCRIPTION
**Pull request by Pyko1**
:cl: Pyko
tweak: Carbon didin't get a date for valentines day,  and neither do you. Valentines day now has 0% chance of happening.
/:cl:

### CODE REVIEW

**Comment by Carbonhell** [comment]
Mfw i need to pass valentine's day alone and with a 40°C fever...
Horrible holiday

**Comment by Pyko1** [comment]
well at least no one else gets a date either after this.

**Comment by Jujumatic** [comment]
Jokes on you I'm going on a date with my hand

**Comment by Pyko1** [comment]
The chances are, that you wont be having hands after this PR is merged.

**Comment by Jujumatic** [comment]
Fuck... wait just direct commit it out ;)

**Comment by Lxtoofonea** [comment]
+1, i hate love

**Comment by TheMeatGod** [comment]
+1

**Comment by DaydreamPuppeh** [comment]
+1

**Comment by Maroonenahmoron** [comment]
+1, no ERP allowed.

**Pull request merged**
