### PR TITLE
buff supermatter

### PR DESCRIPTION
**Pull request by k-k-karma**
for Zyz

### CODE REVIEW

**Comment by yoyobatty** [comment]
??

**Comment by funkynuggets** [comment]
Yes. also fucking say what you changed retard

**Comment by k-k-karma** [comment]
I BUFFED IT YOU DUMB FUCKER WAHT DOES IT LOOK LIKE

**Comment by DaydreamPuppeh** [comment]
Tell us what you buffed

**Comment by funkynuggets** [comment]
you don't say how you buffed it retard smh

**Comment by k-k-karma** [comment]
explosion and rads

**Comment by DaydreamPuppeh** [comment]
+1

**Comment by yoyobatty** [comment]
Make a changelog please.

**Comment by k-k-karma** [comment]
when it's approved

**Comment by yoyobatty** [comment]
You've given a vague description and expect people to approve it, that sounds like you're intentionally trying to implement a drastic change without telling anyone what it does.

**Comment by uBadush** [comment]
He increased the radiation by 175x when it explodes lol

**Comment by uBadush** [comment]
And explosion power by in 100x

**Comment by uBadush** [comment]
Basically everyone will does if it delaminates

**Comment by uBadush** [comment]
Karma send us a video of it delaminating

**Comment by yoyobatty** [comment]
Lol so make a subtype of supermarket and just call it adminbus

**Comment by uBadush** [comment]
More tools for manly to end a round

**Comment by Jujumatic** [comment]
this basically means the entire z level will die even if the sm delaminates for some retarded poopy reason, and if you don't immediately die from the explosion you sure as fuck will from the rads within a minute

**Comment by Maroonenahmoron** [comment]
Make it an admin event where we can make the supermatter unstable and if it somehow delaminates, kaboom has above.

**Comment by yoyobatty** [comment]
Too memey

**Pull request closed without merging**
