### PR TITLE
removes 1directional windows in engine area

### PR DESCRIPTION
**Pull request by Spacedong**
because retards kept getting stuck trying to get to the middle field generators

:cl: Spacedong
del: Removed one-directional plasma windows in the engine area.
/:cl:

### CODE REVIEW

**Comment by banthebantz** [comment]
Tested and mapmerged I assume?

**Comment by Spacedong** [comment]
yes

**Comment by Chnkr** [comment]
Too safe, -1

**Comment by MoreRobustThanYou** [comment]
-1 just rearrange the rad collectors

**Comment by Spacedong** [comment]
why the fuck are you -1ing it it literally makes it easier to get the one in the middle, thats why this space is here, 
image

**Comment by Spacedong** [comment]
it doesnt matter how you rearrange the collectors, so long as the windows are there (which are actually useless, they serve no purpose) it will be a pain in the ass

**Comment by banthebantz** [comment]
I don't care about the looks +1

**Comment by McBawbaggings** [comment]
tbh i had to deconstruct the windows once to on the middle right barrier because it shut off
it bothers me too so i'm good with removing the glass panes.

**Comment by dreamcrab** [comment]
+55555 fuck the dumb windows

power either never gets set up or it gets loose because the containment fucks up

**Comment by Dudeinyourbackyard** [comment]
go ahead, mr. joesterr

**Comment by MoreRobustThanYou** [comment]
that's +3

**Pull request merged**
