### PR TITLE
mapfix

### PR DESCRIPTION
**Pull request by Pyko1**
fixes map issues caused by maprebase or what ever

### CODE REVIEW

**Comment by Pyko1** [comment]
DNM adding more fixes

**Comment by Pyko1** [comment]
should be fine now, fixed some wires/airlock fans as well as missing mech

**Comment by yoyobatty** [comment]
my fixes just got merged so you might have to update your shit bro just letting you know

**Comment by Pyko1** [comment]
or jsut close, no point for 2 people to work fixing the map

**Pull request closed without merging**
