### PR TITLE
Security rework that dwarf made and I just stole lmao

### PR DESCRIPTION
**Pull request by karmaisblackandbluepilled**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:Yoyobatty, SatouOnBroadway/Navi.OS, Shazzzbot, Gannets, b i t e m e
add: Security looks better™
add: The Abzats Machineshotgun is back, just as you remember it!
add: Added the AK-922, a classic gun, complete with its golden variant.
add: The Syndicate Tophat, a fancy traitor item that was originally meant to be a replacement for the balloon. It's here though, so
imageadd: Security now has brand new sprites. Oy, guvna.
imageadd: Numerous nukie guns and ammo now have new sprites.
tweak: The L6 SAW now fits on your back.
/:cl:

## About The Pull Request
I will nuke the illegitimate state of :flag_il:
this is actually just #11696

## Why It's Good For The Game
poop shit cum fuck ass 
quote from old pr
"The gun sprites were made by Shazbot from CEV Eris, the Golden AK was tuned up by SatouOnBroadway/Navi.OS.
Nuke Op suit sprites by b i t e m e, from Tau Ceti.
Security sprites by Gannets, from Goonstation.
All of the code that I didn't understand got passed to Yoyobatty, from Canada. I paid him in syrup."

### CODE REVIEW

**Comment by karmaisblackandbluepilled** [comment]
something's wrong, I can feel it

**Comment by Punkinguy** [comment]
+10000 accepted

**Comment by mkikt4743** [comment]
yeah

**Comment by Punkinguy** [comment]
my god this actually happening

**Comment by mkikt4743** [comment]
very cool can we get some pics of new sprites? either way +1

**Comment by carlopault** [comment]
what exactly is reworked, I wasnt around/didnt pay attention back when Dwarf made this

**Comment by ProtozoaPrime** [comment]
for carlos / general use, here's a link to the related [forum post](https://forums.hippiestation.com/viewtopic.php?f=20&t=1450)

**Comment by MrEpicSax** [comment]
+1

**Comment by karmaisblackandbluepilled** [comment]
note, more than half the things in that forum post aren't in. What we have is the nukie guns and the security clothes.

**Comment by AnthonyJNgo** [comment]
-3 for now, we really need to have this discussed in a new forum thread and really pick it piece by piece to ensure we want all of the changes.

**Comment by Fikou** [comment]
>security rework
>practically nothing about security changes, its just new nukie guns

**Comment by carlopault** [comment]
+2 after hearing what exactly is being added

**Comment by cris5311** [comment]
+1 
we have been waiting for this

**Comment by yoyobatty** [comment]
This should be test merged.

**Comment by Zyzarda** [comment]
+1 Dwarf handcrafted this out of pure ingenuity

**Comment by mkikt4743** [comment]
new armor looks fucking ugly change back

**Comment by karmaisblackandbluepilled** [comment]
no

**Comment by mkikt4743** [comment]
-1

**Comment by Manly-Dwarf** [comment]
Hey, just so you know the code for the syndicate tophat is terrible and needs to be rewritten.
Also, since the Security Overhaul was originally supposed to be an update that dealt with both Nuke Ops, greytide _and_ Security, you may notice that the PR that I uploaded was 90% syndie content and basically only just sprites for Security. I barely actually got anywhere on it since I got stumped pretty fast on the code and then burned out. So you may want to remove the "add: Completely reworked Security" from the PR for now, unless you plan on finishing the whole thing in one go.

**Comment by karmaisblackandbluepilled** [comment]
ok king

**Comment by AnthonyJNgo** [comment]
Merge conflicts

**Comment by karmaisblackandbluepilled** [comment]
fuk

**Comment by karmaisblackandbluepilled** [comment]
>too complex to resolve in web editor
REEEE

**Comment by karmaisblackandbluepilled** [comment]
gonna remove the hat since it doesn't actually work, so says dwarf

**Comment by karmaisblackandbluepilled** [comment]
or am I

**Comment by karmaisblackandbluepilled** [comment]
shit dude, I fucked it up
what the hell did I do even

**Comment by karmaisblackandbluepilled** [comment]
wait no I didn't. Github is hell. @yoyobatty please look over this to figure out if I fucked something up, if not, merge it since it has the votes.

**Comment by karmaisblackandbluepilled** [comment]
wait how the fuck did I even dismiss a review

**Comment by t-f-w** [comment]
+1

**Comment by mkikt4743** [comment]
yucky armor sprites still in?

**Comment by AnthonyJNgo** [comment]
Need an update on this if you want it to stay open.

**Comment by carlopault** [comment]
Lunaman slacking on this PR

**Comment by karmaisblackandbluepilled** [comment]
good catch

**Pull request closed without merging**
