### PR TITLE
Makes the forge bullets all change into the same caliber at once

### PR DESCRIPTION
**Pull request by karmaisblackandbluepilled**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
tweak: Our new and improved casings now change into the same caliber as the master one all at once!
/:cl:

## About The Pull Request
2 days down the drain, thank you chad yoyo and chad Neo for putting up with my bitchass. This code was made by Neo.

## Why It's Good For The Game
eaugh oof my dick

### CODE REVIEW

**Comment by yoyobatty** [comment]
You may want to specify this only applies to the turf you're standing on, as people might think it would compensate for the stuff in your bag.

**Comment by MrEpicSax** [comment]
+1 speedmerge kek

**Comment by karmaisblackandbluepilled** [comment]
i put it in the new desc of the casing that it works for bullets under you

**Comment by AnthonyJNgo** [comment]
+3 good change

**Comment by mkikt4743** [comment]
yeah

**Comment by cris5311** [comment]
+1
speedmerge

**Pull request merged**
