### PR TITLE
Removes antistun from hulk - keeps wall punching

### PR DESCRIPTION
**Pull request by k-k-karma**
:cl: karma
balance: hulk has no antistun anymore
/:cl:

If this is merged I will rebalance hulk fully in a different PR but I dont want to do it now without knowing if it'll be accepted or not

### CODE REVIEW

**Comment by Kawaii-Big-Boss** [comment]
+1 remob anteestun

I'd still prefer buffing Hulk in some way to compensate, like instant aggro grabs without slowdown and better throwing or something like that, but this has been a long time coming.
If you're concerned about this making hulk too easy, you still can't cuff hulk.

**Comment by k-k-karma** [comment]
yeah I'll buff hulk if this gets merged

**Comment by t-f-w** [comment]
figgin ebin +1

**Comment by zamolxius** [comment]
let hulks pull your limbs off with throat grab (works on any limb though if you aim at one)

**Comment by Lxtoofonea** [comment]
Ether make hulks valid or remove there anti stuns +1

**Pull request merged**
