### PR TITLE
The Bar Unfuckening

### PR DESCRIPTION
**Pull request by PopNotes**
:cl: PopNotes
tweak: Rearranged the bar behind the counter- and to some degree in the backroom- to be less awful and promote robust bartending. Some examples are: Moved around the dispensers and vendor so you can access them all from the same tile, put the shaker in front of you when you spawn and added a chemtank to the working area for storing/vending mixed drinks easily (with a screwdriver in the materials closet).
/:cl:

Preview:

### CODE REVIEW

**Comment by PopNotes** [comment]
why do I always forget to name my fucking PRs

**Comment by GuyonBroadway** [comment]
HOLY NOT MAPMERGING BATMAN!!

**Comment by DinduStuffin** [comment]
I give a +1 for this as a concept but if it's having issue merging then no
i'm lazy though so when it merges fine just assume I gave it a +1

**Comment by PopNotes** [comment]
por que

**Comment by McBawbaggings** [comment]
you didn't map merge which means it's a huge ass file change

i think it's still fine to merge though, just will mean downloading the changes for everyone else will be more lengthy

**Comment by McBawbaggings** [comment]
basically in the maps tool folder, you run the prepare maps batch, make your changes, save, run the map merge batch on the map you changed and commit that new map

it saves a lot of line changes

**Comment by PopNotes** [comment]
oh yeah that's so much better

**Comment by bardofrage** [comment]
sure +1

**Comment by McBawbaggings** [comment]
nice and good +1

**Comment by 2Dollarbill** [comment]
+1, bar changes are always gucci.

**Comment by PopNotes** [comment]
bruh it got merged

**Pull request merged**
