### PR TITLE
Death Squid

### PR DESCRIPTION
**Pull request by Pyko1**
:cl: Pyko
add: Adds Death Squid
/:cl:

WIP, Only icon at the moment to test icondiffbot

All credits to Satou Tatsuhiro for the icons.

### CODE REVIEW

**Comment by Pyko1** [comment]
Suggestions?

Thinking of making it a subtype of magic carp, with some changes.
Possibly drops a staff on kill?
Hence more dangerous?

Somekind of nerfed goliath tentacle attack?

**Comment by praisenarsie** [comment]
smh it's not an Ichthyosaur.

**Comment by JohnGinnane** [comment]
cool icon bot

**Comment by Spankmonkey777** [comment]
Goliath tentacle would be cool, maybe it could snag people and drag them into it.

**Comment by ExpAntique** [comment]
Let the wizard shape-shift into it instead of being a chaos magi-carp. it can have two hands, with a chaos staff that can only be dropped on death or if stunned, and another hand that's always a ling tentacle.

**Comment by McBawbaggings** [comment]
tie it into wizard events i think
they should SPEW OUT from a portal in a certain area, and generally be dangerous guys that shoot daeth bolts

**Comment by Pyko1** [comment]
Closing this for now, until I or anyone else figures out what they want to do with the icon.

**Pull request closed without merging**
