### PR TITLE
Renames Assistants to better reflect what they do

### PR DESCRIPTION
**Pull request by Pyko1**
:cl: Pyko
tweak: Assistants are now called as Assailants
/:cl:

Assistant don't really assist anyone, I believe Assailant is a far more better job tittle for them.

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
Don't forget to change the spawn point defines too, else we get a situation like when spacedong renamed cook back to chef and they suddenly spawned in the brig.

**Comment by Pyko1** [comment]
good point, if anything we definitely dont want invisible assailant when specco fixes this.

**Comment by fluxcapacitor1337** [comment]
+1

**Comment by Pyko1** [comment]
I wonder if I should PR this upstream :3

**Comment by Pyko1** [comment]
I think it should now all be assailant

**Comment by Pyko1** [comment]
need to check icons and fix shit

**Comment by Pyko1** [comment]
No time to fix now, but should be ready for sunday.

**Comment by Carbonhell** [comment]
eww -1

**Comment by Kawaii-Big-Boss** [comment]
fucking finnish loser trying to rename our glorious greytide

**Comment by Dinopeaks** [comment]
-1 i have seen one help

**Pull request closed without merging**
