### PR TITLE
Deathsquad race, ert outfit and armour nerf

### PR DESCRIPTION
**Pull request by karmaisblackandbluepilled**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
tweak: removed some traits from the DS
tweak: changed the corporate race to deal less damage from unarmed melee, and to take more. also lower chance of stunning from melee
tweak: made the ds hardsuit shittier
balance: made ds start out with a normal, non-loyalty pulse rifle
balance: changed what shield deathsquads start out with, it's the classic eshield now
balance: changed what macrobomb ds start out with, normal macrobomb now
/:cl:

## About The Pull Request
byond actually threw a bug my way when I tried to compile this

## Why It's Good For The Game
because karma turned the deathsquads from something that can be beaten to something that literally doesn't take damage from pulse destroyers. if you want to make an unbeatable ert just spawn them seraphs or give them admin items ffs

### CODE REVIEW

**Comment by QuarianCommando** [comment]
-1 We don't send in the deathsquad unless we want the round to end.

**Comment by karmaisblackandbluepilled** [comment]
at that point just activate the nuke if you want it to be over, ds should be a thing that people can fuck with instead of being delayed death

**Comment by wheezl** [comment]
+1, deathsquad should be powerful but not invincible

**Comment by zamolxius** [comment]
+1, deathsquad should be powerful but not invincible
also make them gib when hearing a randomly generated killcode phrase

**Comment by Manly-Dwarf** [comment]
-1
deathsquad is the "fuck you" for a reason. if you really wanted to nerf them you should remove their macrobombs.
challenge is ERT, "fuck you" is deathsquad.

**Comment by steamp0rt** [comment]
i say make them possible to kill, but pretty hard

**Comment by mkikt4743** [comment]
deathsquad ez to kill as zombie, hit them once and it's over

**Comment by cris5311** [comment]
+1
if you want to fuck you a guy just blow up the nuke, DS shoulnt be virtually immortal

**Comment by SireTurret** [comment]
-1

First of all, the admins should use their grey matter to determine when it's the time to send in a DS. I usually sent one after the antags killed the code red ERT, which is fair.
It's POSSIBLE to kill deathsquaddies. Not all 5 of them, but at least a few. I can attest that.

Also how about you people just send in fucking code reds? They're basically downgraded deathsquadides.

**Comment by DON-KARMA** [comment]
FUCK OFF YOU RETARD THEY'RE SUPPOSED TO BE INVINCIBLE STOP SENDING DEATHSQUADS IN IF YOU DONT WANNA WIN USE FUCKING ERTS HOLY SHIT

**Comment by DON-KARMA** [comment]
WHAT IS THE POINT OF USING A DEATHSQUAD IF IT'S GOING TO DIE ANYWAYS? DEATHSQUADS WERE FUCKING USELESS BEFORE MY BUFFS BECAUSE CODE RED ERTS WERE BETTER

**Comment by DON-KARMA** [comment]
KILL YOURSELF

**Comment by steamp0rt** [comment]
Saw that coming from a million miles away

**Comment by steamp0rt** [comment]
also please avoid saying stuff that might trigger the Github Feelings Police, i don't want ya'll getting github-banned

**Comment by DON-KARMA** [comment]
STOP DELETING MY COMMENTS NIGGER

**Comment by steamp0rt** [comment]
your loss if you get githubbanned

**Comment by DON-KARMA** [comment]
i've been github banned twice retard

**Comment by DON-KARMA** [comment]
SERIOUSLY THOUGH WHAT IS THE FUCKING POINT OF MAKING DEATHSQUADS LITERALLY FUCKING USELESS

**Comment by DON-KARMA** [comment]
A CODE AMBER ERT IS BETTER THAN THIS PILE OF SHIT YOU'VE PUT OUT

**Comment by FantasticFwoosh** [comment]
Ok boomer.

That besides i have no personal issue making DS 'weaker' as long as it doesn't give admins free justification to send them rather than just a well equipped ERT. Some entertaining flukes in the future.

**Comment by TrickyDickRichard** [comment]
deathsquad is something you call when 1. there are many people that have been taken out of the round and 2. you have already tried to put people back into the round(like with ERT or vigilantes if we used them) but they have all died as well. why would you make them weaker

**Comment by danhibiki** [comment]
It’s been said ad naseum, but deathsquad doesn’t need a nerf. It’s a end of round admin spawned event, you aren’t suppose to be able to easily kill them, the point is they end the round

**Comment by karmaisblackandbluepilled** [comment]
I don't agree with y'all saying that DS ends the round. If you want to end the round activate the nuke/send warops or some shit. DS is just unbeatable currently.
also it'd make karma mad which is good

**Comment by Manly-Dwarf** [comment]
no go away

**Pull request closed without merging**
