### PR TITLE
added new sprite for triple barrel shotty made by mist furor

### PR DESCRIPTION
**Pull request by karmaisblackandbluepilled**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
add: Added new sprite that looks better™
/:cl:

## About The Pull Request
Despite

## Why It's Good For The Game
1%

### CODE REVIEW

**Comment by karmaisblackandbluepilled** [comment]
image

**Comment by yoyobatty** [comment]
In game screenshot thou?

**Comment by karmaisblackandbluepilled** [comment]
fug, i gotta build it to check it
also merge canegun

**Comment by karmaisblackandbluepilled** [comment]
Capture

**Comment by QuarianCommando** [comment]
+1

**Comment by notoriousBIGGIOS** [comment]
+1

**Comment by TrickyDickRichard** [comment]
I Guess It Looks More Epicer +1...

**Pull request merged**
