### PR TITLE
Revert "Removes roundstart clown car"

### PR DESCRIPTION
**Pull request by KingTerrytheTerrible**
Reverts HippieStation/HippieStation#9645

### CODE REVIEW

**Comment by Toxici11i** [comment]
+1 clown funny

**Comment by Manly-Dwarf** [comment]
no it ruined the clown job

**Comment by karmaisblackandbluepilled** [comment]
+1 clown funny

**Comment by KingTerrytheTerrible** [comment]
> 
> 
> no it ruined the clown job
> some things should remain traitor exclusive

it's funny, just smite people who abuse it

**Comment by Manly-Dwarf** [comment]
that would be literally every single clown. in fact I am tempted to close this any way due to how much of a nightmare it was for admins as well.
clowns didn't have to try when we added it. they charged it first thing every round and started running into as much people as possible. then the clown car broke, which of course explodes and dented the station. if anyone decided to not leave the clown car, you could guarantee they were ahelping and saying "HoS killed me."
you could superfart while in the clown car as well, which had similar problems.
clowns would even ahelp if you destroyed the car roundstart or killed them the moment you saw them enter the car. it started becoming a "if you get in the clown car you're valid" situation, which turned out to be stupid as the clown car was horrible to begin with and should have remained for traitors.

you didn't bother to fix any of this, pretty much guaranteeing the cycle will repeat. plus, clowns ran for the clown car immediately when a round started. you don't have to be robust to annoy the entire station with the clown car, it costs nothing, every clown gets it instantly when the round starts and every single clown used it. the joke got run into the ground so fast and so hard after admiral made his video and made clowning way too easy.
it's garbage in its current implementation and it's a garbage idea in general. leave it as a traitor item.

**Comment by KingTerrytheTerrible** [comment]
thats why its so fucking funny

**Comment by KingTerrytheTerrible** [comment]
literally everyone but you wants it back

**Comment by Manly-Dwarf** [comment]
never heard that one before
it had its heyday but the joke is old now and not funny at all. by the time admiral made his video, the joke was played out and everyone started treating the clown car as a traitor item.
it's much funnier when clowns have to be traitors to use it since that means the joke isn't on repeat every single round.

**Comment by karmaisblackandbluepilled** [comment]
instead of it always being in, make it have like a 10% or 5% of spawning every round

**Comment by wheezl** [comment]
+1 but only if it's put in the armory instead, maybe make some flavor text about it getting repo'd. otherwise -1

**Comment by KingTerrytheTerrible** [comment]
armory clown car sounds fantastic but i dont know how to map so

**Comment by Manly-Dwarf** [comment]
you fiend

**Comment by mikolaj007** [comment]
-1

**Comment by QuarianCommando** [comment]
+1, but the clown has to be made valid if he enters it, and there needs to be a centcom announcement with location every time someone gets in the clown car.

**Comment by yoyobatty** [comment]
Yeah it's funny for a few rounds then it pisses everyone else off and it gets removed again.

**Comment by diegoxt45** [comment]
this shouldn't be an argument wtf just close this already

**Comment by mkikt4743** [comment]
just make it one less TC so clown can emag it lol -1

**Comment by cris5311** [comment]
-1 very gay

**Comment by cris5311** [comment]
+1 clown funny

**Comment by cris5311** [comment]
and also +1 for making you valid for using it

**Comment by MrEpicSax** [comment]
+1 But how about they bleed out while using it?

**Comment by MrEpicSax** [comment]
Or I guess you could just have it so you're not sucking people up and they have to choose to get in. Leave that for the tot clown car.

**Pull request closed without merging**
