### PR TITLE
Adds Mouse Facing

### PR DESCRIPTION
**Pull request by karmaisblackandbluepilled**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
add: You automatically face where your mouse is pointing. This can be disabled in preferences.
/:cl:

## About The Pull Request
fun fact as you can tell by the branch name i actually wanted to add a portable music player with custom uploading capabilities at first but tgcode does not have positional sounds apparently
Ported from Interhippie

### CODE REVIEW

**Comment by karmaisblackandbluepilled** [comment]
aaaa I forgot to test disabling it aaaa

**Comment by karmaisblackandbluepilled** [comment]
i also forgot to add it to the savefile
braincancer perhaps yes

**Comment by karmaisblackandbluepilled** [comment]
i fixed it time to annoy the admins

**Comment by Zyzarda** [comment]
Sounds sweet, optional shit is always +2

**Comment by karmaisblackandbluepilled** [comment]
MGUIgDeZ1L

**Comment by mkikt4743** [comment]
what is wrong with your cursor lunaman

**Comment by Punkinguy** [comment]
+1

**Comment by karmaisblackandbluepilled** [comment]
roblox cursor is based

**Comment by carlopault** [comment]
Move in the opposite direction of your cursor

**Comment by cris5311** [comment]
+1

**Comment by enthethan** [comment]
What is the point

**Comment by carlopault** [comment]
+2 now you dont have to move your character to face someone during convo

**Comment by yoyobatty** [comment]
Test merge time?

**Comment by carlopault** [comment]
> Test merge time?

yes

**Comment by karmaisblackandbluepilled** [comment]
no

**Comment by carlopault** [comment]
why close

**Pull request closed without merging**
