### PR TITLE
Spurdo Spadre mask usable as a gas mask

### PR DESCRIPTION
**Pull request by karmaisblackandbluepilled**
:cl:
tweak: spurdo mask is now usable as a gas mask
/:cl:

## About The Pull Request
destroy the :flag_il:

## Why It's Good For The Game
fard

### CODE REVIEW

**Comment by wheezl** [comment]
+1

**Comment by mkikt4743** [comment]
yeah

**Comment by carlopault** [comment]
+! 01101100 01100101 00100000 01100101 01110000 01101001 01100011 00100000 01110000 01100101 01100101 01110000 01100101 01100101 00100000 01110000 01101111 01101111 01110000 01101111 01101111

**Comment by MrEpicSax** [comment]
+1 I don't even know if my vote is even worth anything. I just like upping things.

**Comment by Timmeye** [comment]
+1 I don't even know if my vote is even worth anything. I just like upping things.

**Comment by cris5311** [comment]
+1
do i need to explain?

**Comment by Punkinguy** [comment]
+1 very goode!

**Pull request merged**
