### PR TITLE
Nova/Galaxyfarting now plays the Goon superfart sound, audible to everyone.

### PR DESCRIPTION
**Pull request by PopNotes**
:cl: PopNotes
soundadd: Novafarts and Galaxyfarts are now audible from everywhere on the station. Sound credit goes to Goonstation.
/:cl:

brap

### CODE REVIEW

**Comment by Blute1** [comment]
lmfao, make this the fucking mega-superfart noise, braps so powerful they gib you

**Comment by dreamcrab** [comment]
is their command just *superfart too? i have to go check it out before i comment a yes/no on this

**Comment by tortellinitony** [comment]
yeah make this the sound for when you explode or something

**Comment by PopNotes** [comment]
I might actually do that for nova/galaxyfarts

**Comment by dreamcrab** [comment]
yes i like this new form of the pr 

yes
+666666666666666666666

**Comment by bardofrage** [comment]
+1

**Comment by PopNotes** [comment]
why would it lag

**Comment by banthebantz** [comment]
byond soundcode + 1000 tile radius

**Comment by PopNotes** [comment]
also the volume changes were merged in #4680

**Comment by PopNotes** [comment]
changed extrarange from 1000 to 255

**Comment by MoreRobustThanYou** [comment]
You could just loop through all the players and playsound_local

**Comment by PopNotes** [comment]
nah

**Comment by banthebantz** [comment]
+1

**Pull request merged**
