### PR TITLE
Text floats over your head.

### PR DESCRIPTION
**Pull request by karmaisblackandbluepilled**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

I tried to give it a runescape font but maptext doesn't work with custom TTFs.

## Changelog
:cl:
add: Whatever you say floats over your head.
/:cl:

## About The Pull Request
thank you Cthulhuonice, spacemaniac from the coderbus and burger from burgerstation

### CODE REVIEW

**Comment by karmaisblackandbluepilled** [comment]
i forgot pics hold on

**Comment by karmaisblackandbluepilled** [comment]
dreamseeker_dNpKDjvQWG
dreamseeker_P505aIiOKG
dreamseeker_EPWPieIZIj
dreamseeker_CuQvhUId8B

**Comment by cris5311** [comment]
+1, are there checks to stop it from covering the whole screen?

**Comment by carlopault** [comment]
+2 same question as cris, are there checks?

**Comment by karmaisblackandbluepilled** [comment]
yeah that last pic is the limit

**Comment by Zyzarda** [comment]
+2 based and surprisingly useful

**Comment by illusineer** [comment]
cool

**Comment by byandaccount** [comment]
+1 i love everything about this

**Comment by MrEpicSax** [comment]
+1 can we customise the colour?

**Comment by karmaisblackandbluepilled** [comment]
no, the text is random

**Comment by MrEpicSax** [comment]
aww..

**Comment by carlopault** [comment]
The faster this gets merged the better

**Pull request merged**
