### PR TITLE
Revert "Shuttle be gone"

### PR DESCRIPTION
**Pull request by k-k-karma**
Reverts HippieStation/HippieStation#11075

### CODE REVIEW

**Comment by mikolaj007** [comment]
-1

**Comment by Majick1** [comment]
-1 karma pls

**Comment by yoyobatty** [comment]
Grief shuttle

**Comment by Manly-Dwarf** [comment]
-1

**Comment by ExpAntique** [comment]
-1 Karma be gone

**Comment by HideAndSeekLOGIC** [comment]
Headmin -1, close time

**Comment by k-k-karma** [comment]
you need more than that

**Comment by mikolaj007** [comment]
-2 from designers, -2 from maintainers, -1 from headmin, -1 from a random
>
>you need more than that
>
HMMMMMMMM

**Pull request closed without merging**
