### PR TITLE
returns our nice looking shuttle chairs

### PR DESCRIPTION
**Pull request by Pyko1**
:cl: Pyko
fix: fixed the ugly tg shuttle chairs
/:cl:
I should prolly test this when i have time, before anyone merges this...

### CODE REVIEW

**Comment by fluxcapacitor1337** [comment]
+1

**Comment by fluxcapacitor1337** [comment]
whoever coded this probably needs to experience some kinds of real life consequences

**Comment by Dinopeaks** [comment]
+1 the above comment and also as much as the war is raging with pyko he made a good fix

**Comment by Pyko1** [comment]
I wonder if I should had made them spawn normal chair and then qdel on initialize instead.

**Comment by Jujumatic** [comment]
@Pyko1 is this ready aaaaah

**Comment by JohnGinnane** [comment]
@Pyko1 I wrote some functionality specifically to allow us to override tg chairs without issue, is it not working or something?

**Comment by JohnGinnane** [comment]
Oh they added a new object. All we need to do is set `icon_state` to `chair` and the rest of the code will take over. You can change the name and description if you want. The override on `init()` is unnecesarry, unless you want to chaneg the overlay as well

**Comment by Pyko1** [comment]
welp they new changed them to comfy shuttle chairs...

**Pull request closed without merging**
