### PR TITLE
BUFFS TANX

### PR DESCRIPTION
**Pull request by PopNotes**
:cl: PopNotes
tweak: chemtanks are back to the way they used to be at 1000u capacity
/:cl:

Ree

300u chemtanks are bad, let's bring 'em back to the good old days of glorious 1000u

### CODE REVIEW

**Comment by JamieH** [comment]
yes it requires a changelog

**Comment by tortellinitony** [comment]
No thanks

**Comment by PopNotes** [comment]
It's extremely obvious if you're going to use it for destructive purposes and having what's essentially a stationary 1000u capacity beaker is an absolute godsend for mass-producing chems like synthflesh.

**Comment by tortellinitony** [comment]
You didn't answer my question.

**Comment by PopNotes** [comment]
I did.

The great thing about beaker grenades is versatility. You can get pyro casings for bomb grenades, advanced release casings for gradual 'drip' effects, and a whole variety of triggers to make them do exactly what you want, how you want, when you want.

You don't _get that_ with chemtanks. You get a big, obvious single container that can't be fit into your pockets nor your backpack.

**Comment by GuyonBroadway** [comment]
We also had 1000u chemtanks pre rebase and you could open and empty ANY tank and fill it up with ANYTHING.

Chemtanks are now harder to get and as popnotes said they are far less versatile and far more obvious than a beaker or grenade. And if you wanted a 300u bomb you could let off at any time you can literally fill a bottle of space cleaner with 295u black powder, drop 5u of hot as fuck water in there, drop it and run like hell.

**Comment by tortellinitony** [comment]
They are far less versatile and you can't put them in a pocket, correct. But they have as much volume as a bluespace beaker, which takes effort to get. You can find chem tanks laying around in maintenance. I think making them this large is completely fair and raising them to 1000 units would be completely overkill. Saying that something was a certain way before rebase is a shit excuse to have it that way now.

**Comment by GuyonBroadway** [comment]
A bluespace beaker takes effort to get due to its ability to create powerful grenades. A large cintainer isn't overkill when the worst you could do with it is spend a lot of time making clf3 and setting some of the station on fire. 

Most of the use of a 1000u tank would be to let the clown spread carpet everywhere or make eveything multicoloured.

And again, they only spawn rarely and you cannot make new ones so are still not as big a thing as they were pre-rebase.

**Comment by tortellinitony** [comment]
No, the primary use would be black powder bombs. Chem tanks spawn in set locations like they did pre-rebase. If a bluespace beaker was previously the only container that large, how can you say its purpose is only to make grenades? That is a stupid claim.

**Comment by GuyonBroadway** [comment]
It wasn't the only container that large, you can use spacecleaner bottles for the same purpose.

And yes bluespace beakers main reason was to cram more chems in a grenade for larger effects, they were hardly used for anything else.

**Comment by Pyko1** [comment]
As long as you cant put chemtanks inside a chemdispenser, the bluespace beaker has its advantage.

**Comment by Carbonhell** [comment]
I agree with this pr honestly, i coded those originally and i had the same line of thought, plus in the months it was in, noone found a way to abuse those, so i think it's pretty safe. Hell, i hardly saw this mechanic used, even.

**Comment by JamieH** [comment]
Merging because they're different to bluespace beakers

**Pull request merged**
