### PR TITLE
Removes ear rape

### PR DESCRIPTION
**Pull request by PopNotes**
:cl: PopNotes
soundadd: The 'traps are gay' round end sound no longer perforates your ear drums. God damn it, thefastfoodguy.
/:cl:

### CODE REVIEW

**Comment by McBawbaggings** [comment]
+1

traps are gay though

**Comment by PopNotes** [comment]
agreed

**Comment by bardofrage** [comment]
+1 but traps are still gay, that has not changed.

**Comment by banthebantz** [comment]
filthy trap lovers

**Comment by PopNotes** [comment]
we can all agree that traps are gay and tinnitus is bad

**Pull request merged**
