### PR TITLE
Bananium in the miner

### PR DESCRIPTION
**Pull request by karmaisblackandbluepilled**
## Changelog
:cl:
tweak: Added bananium to the bluespace miner.
/:cl:

## About The Pull Request
Clowns shall help :flag_sd: to destroy :flag_il:

## Why It's Good For The Game
hyonk

### CODE REVIEW

**Comment by MrEpicSax** [comment]
+1 speedmerge pls

**Comment by carlopault** [comment]
how much bananium

**Comment by AnthonyJNgo** [comment]
+3 if bananium is made as rare as diamonds as it should be.

**Comment by karmaisblackandbluepilled** [comment]
it's 150, not 90 like diamonds

**Comment by carlopault** [comment]
idk if 150 is a lot or not so I will just say make it 90 like diamonds and then  +2

**Pull request merged**
