### PR TITLE
Noi-Sie

### PR DESCRIPTION
**Pull request by PopNotes**
🆑 PopNotes
soundadd: Nar-Sie now actually sounds like an eldritch abomination that obliterates worlds instead of a sweet maiden that gently whispers sweet nothings in your ear.
/🆑

Sound entirely made by me making various guttural noises into a microphone and then fucking with them using audacity.

Here's a preview. http://puu.sh/wHm7V/92992edbcd.wav

First PR didn't fly so good, let's try again.

### CODE REVIEW

**Comment by PopNotes** [comment]
goddamn it what the fuck

**Comment by FuryMcFlurry** [comment]
Sounds good

**Comment by McBawbaggings** [comment]
very nice
+1

**Comment by Dudeinyourbackyard** [comment]
yeah cool

**Comment by Chnkr** [comment]
You mirrored the entire nar-sie file, why the fuck

**Comment by PopNotes** [comment]
what the fuck do you expect me to do

**Comment by Carbonhell** [comment]
For a single line change you can just directly edit the tg file imo.

**Comment by PopNotes** [comment]
I tried that and it gave me conflicts, why do you think I went to the trouble of putting all this crap in the hippiestation folder

**Comment by tortellinitony** [comment]
We're not mirroring the entire file for one stupid sound. Find a better way to do it.

**Comment by PopNotes** [comment]
fucking _give_ me a better way to do it then

**Comment by tortellinitony** [comment]
That's not anybody's job. Figure it out yourself.

**Comment by PopNotes** [comment]
You people put in this fucking obtuse /tg/ upstream PR system, not me.

**Comment by banthebantz** [comment]
I actually quite like the subtle _"I'm here"_

**Comment by PopNotes** [comment]
no

**Comment by banthebantz** [comment]
Narsie is a girl with standards

**Comment by FuryMcFlurry** [comment]
whelp

**Pull request closed without merging**
