### PR TITLE
Adds snapping

### PR DESCRIPTION
**Pull request by PopNotes**
:cl: PopNotes
add: You can now snap your fingers with *snap, *snap2 and *snap3 for single, double and triple snaps respectively. Riveting.
/:cl:

Nobody ever asked for this but I did it anyway. Become tacticool with discussed snap commands or just pretend you're from Grease.

Partially inspired by Intruder, a game that is good and should be played, go play Intruder.

### CODE REVIEW

**Comment by banthebantz** [comment]
knuckle cracking when

**Comment by McBawbaggings** [comment]
ss13 asmr traitor roleplay

**Comment by McBawbaggings** [comment]
also i think is kinda cool but the click2 sounds like scissors more than clicking

**Comment by PopNotes** [comment]
Sudden, loud, short-lived sounds are difficult to get right, sometimes. It took a few tries on each to get them to sound like snaps instead of weird sudden peaking noise.

**Comment by McBawbaggings** [comment]
yeah sure +1

**Comment by bardofrage** [comment]
Do it

**Pull request merged**
