### PR TITLE
Adds the OG X-COM Rifle.

### PR DESCRIPTION
**Pull request by karmaisblackandbluepilled**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

## Changelog
:cl:
add: new xcom rifle.
/:cl:

## About The Pull Request
adds the gun, adds it to the techweb, has custom sounds

## Why It's Good For The Game
because xcom reference good

### CODE REVIEW

**Comment by yoyobatty** [comment]
Pics?

**Comment by Toxici11i** [comment]
seems based, willing to +1 even without pics

**Comment by karmaisblackandbluepilled** [comment]
i did what steamport told me to do to modularize it, it might not work
also how do i post pics on git

**Comment by zamolxius** [comment]
just ctrl c it and ctrl v in the posting box

**Comment by zamolxius** [comment]
modularization isn't even hard man.  but we dont have merge bot anymore, why not allow unmodularized

**Comment by yoyobatty** [comment]
Saves us the headache of having to fix code if we Port a TG fix or feature

**Comment by karmaisblackandbluepilled** [comment]
strange, I'm compiling this on my end with DM and it's not giving me any errors
I wonder why appveyor is shitting out errors

**Comment by karmaisblackandbluepilled** [comment]
guess what lads, now the sprites aren't working so I gotta do another commit

**Comment by TrickyDickRichard** [comment]
+1 based

**Comment by notoriousBIGGIOS** [comment]
go suck a black penis +1

**Comment by Dystarra** [comment]
+1 Guns are good. Guns are good! More guns to hog and blow the brains out of everyone's skull. More guns.

**Comment by karmaisblackandbluepilled** [comment]
Capture
here's an image kings

**Comment by steamp0rt** [comment]
Here's how you modularize: 

You move whatever you can into the hippiestation folder, then open up the DME in Dream Maker, find the new files, tick the checkboxes next to them, and then compile.

**Comment by karmaisblackandbluepilled** [comment]
i will throw a rock at you steamport, the notepad++ thing worked perfectly.
also, when I fucking did that nothing worked you gay n
phew nearly got banned from git

**Comment by Manly-Dwarf** [comment]
that sprite is abysmal
never make another PR again

**Pull request merged**
