### PR TITLE
add a remove goonchat OOC button

### PR DESCRIPTION
**Pull request by KingTerrytheTerrible**

### CODE REVIEW

**Comment by karmaisblackandbluepilled** [comment]
+1

**Comment by gardenBanter** [comment]
+1, death to bloat

**Comment by danhibiki** [comment]
Shouldn’t this be placed under the hippie subfolder?

**Comment by KingTerrytheTerrible** [comment]
no mirror bot

**Comment by karmaisblackandbluepilled** [comment]
@danhibiki we stopped doing that once mirror bot died

**Comment by danhibiki** [comment]
IM retard

**Comment by Manly-Dwarf** [comment]
genuinely uninformed, why exactly?

**Comment by karmaisblackandbluepilled** [comment]
goonchat lags when explosions happen or when shotguns with buckshot fire.

**Comment by Manly-Dwarf** [comment]
we fixed the buckshot thing

**Comment by SireTurret** [comment]
this is dumb and really has no normal reasoning behind it except triggering steamp0rt, oldchat doesn't have any useful functions like goonchat does

**Comment by cris5311** [comment]
+1

**Comment by QuarianCommando** [comment]
+1 I miss the old aesthetic.

**Comment by TrickyDickRichard** [comment]
+1 reject modernity embrace tradition

**Comment by steamp0rt** [comment]
options are always fine

**Comment by yoyobatty** [comment]
Is there a way to undo it other then disconnecting and reconnecting?

**Comment by danhibiki** [comment]
Well? You should be able to disable the chat as easily as reenabling it

**Comment by AnthonyJNgo** [comment]
Most likely not, although reconnecting is simple enough, takes like 5 seconds if you do it from the ss13 client.

**Pull request merged**
