### PR TITLE
Fixes legs

### PR DESCRIPTION
**Pull request by k-k-karma**
[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/README.md )

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs )

:cl: optional name here
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

[why]:

### CODE REVIEW

**Comment by Kawaii-Big-Boss** [comment]
Are we sure this fixes legs dividing by zero?

**Comment by Kawaii-Big-Boss** [comment]
@yoyobatty

**Comment by k-k-karma** [comment]
yes they had no maximum damage

**Comment by k-k-karma** [comment]
(max damage defaults to )

**Comment by nichlas0010** [comment]
hippie cant into modularization

**Comment by k-k-karma** [comment]
what do you mean @nichlas0010

**Comment by nichlas0010** [comment]
https://github.com/yogstation13/Yogstation-TG/pull/3907#issuecomment-448729589 what do YOU mean? @k-k-karma

**Comment by k-k-karma** [comment]
you didnt modularize your work

**Comment by k-k-karma** [comment]
you didn't

**Pull request merged**
